In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\sanjay\OneDrive\Desktop\CS50\San Francisco Building Permits\dirty_cafe_sales.csv")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [6]:
df.duplicated(subset=["Transaction ID"]).sum()

np.int64(0)

In [7]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [8]:
df[~df["Transaction ID"].astype(str).str.startswith("TXN_")]

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [9]:
df[df["Transaction ID"].astype(str).str.len() != 11]

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [10]:
df["Item"].value_counts(dropna=False)

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

In [11]:
df["Item"].unique()

<ArrowStringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

In [12]:
df["Item"].isna()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996     True
9997    False
9998    False
9999    False
Name: Item, Length: 10000, dtype: bool

In [13]:


df["Item"] = df["Item"].replace({"Missing value": pd.NA, "missing value": pd.NA, "UNKNOWN": pd.NA, "ERROR": pd.NA, "NaN": pd.NA, None: pd.NA}) 
df["Payment Method"] = df["Payment Method"].replace({"Missing value": pd.NA, "missing value": pd.NA, "UNKNOWN": pd.NA, "ERROR": pd.NA, "NaN": pd.NA, None: pd.NA}) 
df["Location"] = df["Location"].replace({"Missing value": pd.NA, "missing value": pd.NA, "UNKNOWN": pd.NA, "ERROR": pd.NA, "NaN": pd.NA, None: pd.NA})

In [14]:
df["Quantity"].value_counts(dropna=False)

Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
NaN         138
Name: count, dtype: int64

In [15]:
df["Payment Method"].value_counts(dropna=False)

Payment Method
NaN               3178
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: count, dtype: int64

In [16]:
df["Location"].value_counts(dropna=False)

Location
NaN         3961
Takeaway    3022
In-store    3017
Name: count, dtype: int64

In [17]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors="coerce")
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors="coerce")

In [18]:
df["Quantity"] = df["Quantity"].astype("Int64")

In [19]:
df["Quantity"].value_counts(dropna=False)

Quantity
5       2013
2       1974
4       1863
3       1849
1       1822
<NA>     479
Name: count, dtype: Int64

In [20]:
df["Price Per Unit"].value_counts(dropna=False)

Price Per Unit
3.0    2429
4.0    2331
2.0    1227
5.0    1204
1.0    1143
1.5    1133
NaN     533
Name: count, dtype: int64

In [21]:
df["Total Spent"].value_counts(dropna=False)

Total Spent
6.0     979
12.0    939
3.0     930
4.0     923
20.0    746
15.0    734
8.0     677
10.0    524
NaN     502
2.0     497
9.0     479
5.0     468
16.0    444
25.0    259
7.5     237
1.0     232
4.5     225
1.5     205
Name: count, dtype: int64

In [22]:
df["Transaction Date"].value_counts(dropna=False)

Transaction Date
NaN           159
UNKNOWN       159
ERROR         142
2023-02-06     40
2023-06-16     40
             ...
2023-09-24     15
2023-07-30     15
2023-03-11     14
2023-07-22     14
2023-02-17     14
Name: count, Length: 368, dtype: int64

In [23]:
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"], errors="coerce")

In [24]:
df["Transaction Date"].value_counts(dropna=False)

Transaction Date
NaT           460
2023-02-06     40
2023-06-16     40
2023-03-13     39
2023-07-21     39
             ...
2023-09-24     15
2023-07-30     15
2023-03-11     14
2023-07-22     14
2023-02-17     14
Name: count, Length: 366, dtype: int64

In [25]:
df.isna().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   Int64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(2), str(4)
memory usage: 907.3 KB

In [27]:
df.to_csv("clean_cafe_sales.csv", index=False)

In [28]:
verified_df = pd.read_csv("clean_cafe_sales.csv")
print(verified_df.shape)
print(verified_df.isna().sum())

(10000, 8)
Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64