In [295]:
import pandas as pd

df = pd.read_csv(r"C:\Users\sanjay\OneDrive\Desktop\CS50\006.San Francisco Building Permits\Building_Permits.csv\Building_Permits.csv",  low_memory=False)

In [296]:
print(df.shape)
print(df.columns)
print(df.head())
print(df.info())
df.head()

(198900, 43)
Index(['Permit Number', 'Permit Type', 'Permit Type Definition',
       'Permit Creation Date', 'Block', 'Lot', 'Street Number',
       'Street Number Suffix', 'Street Name', 'Street Suffix', 'Unit',
       'Unit Suffix', 'Description', 'Current Status', 'Current Status Date',
       'Filed Date', 'Issued Date', 'Completed Date',
       'First Construction Document Date', 'Structural Notification',
       'Number of Existing Stories', 'Number of Proposed Stories',
       'Voluntary Soft-Story Retrofit', 'Fire Only Permit',
       'Permit Expiration Date', 'Estimated Cost', 'Revised Cost',
       'Existing Use', 'Existing Units', 'Proposed Use', 'Proposed Units',
       'Plansets', 'TIDF Compliance', 'Existing Construction Type',
       'Existing Construction Type Description', 'Proposed Construction Type',
       'Proposed Construction Type Description', 'Site Permit',
       'Supervisor District', 'Neighborhoods - Analysis Boundaries', 'Zipcode',
       'Location', 'Record ID'],
      dtype='str')
  Permit Number  Permit Type            Permit Type Definition  \
0  201505065519            4                      sign - erect
1  201604195146            4                      sign - erect
2  201605278609            3  additions alterations or repairs
3  201611072166            8            otc alterations permit
4  201611283529            6                       demolitions

  Permit Creation Date Block  Lot  Street Number Street Number Suffix  \
0           05/06/2015  0326  023            140                  NaN
1           04/19/2016  0306  007            440                  NaN
2           05/27/2016  0595  203           1647                  NaN
3           11/07/2016  0156  011           1230                  NaN
4           11/28/2016  0342  001            950                  NaN

  Street Name Street Suffix  ...  Existing Construction Type  \
0       Ellis            St  ...                         3.0
1       Geary            St  ...                         3.0
2     Pacific            Av  ...                         1.0
3     Pacific            Av  ...                         5.0
4      Market            St  ...                         3.0

  Existing Construction Type Description Proposed Construction Type  \
0                          constr type 3                        NaN
1                          constr type 3                        NaN
2                          constr type 1                        1.0
3                         wood frame (5)                        5.0
4                          constr type 3                        NaN

  Proposed Construction Type Description Site Permit Supervisor District  \
0                                    NaN         NaN                 3.0
1                                    NaN         NaN                 3.0
2                          constr type 1         NaN                 3.0
3                         wood frame (5)         NaN                 3.0
4                                    NaN         NaN                 6.0

  Neighborhoods - Analysis Boundaries  Zipcode  \
0                          Tenderloin  94102.0
1                          Tenderloin  94102.0
2                        Russian Hill  94109.0
3                            Nob Hill  94109.0
4                          Tenderloin  94102.0

                                    Location      Record ID
0  (37.785719256680785, -122.40852313194863)  1380611233945
1   (37.78733980600732, -122.41063199757738)  1420164406718
2    (37.7946573324287, -122.42232562979227)  1424856504716
3   (37.79595867909168, -122.41557405519474)  1443574295566
4   (37.78315261897309, -122.40950883997789)   144548169992

[5 rows x 43 columns]
<class 'pandas.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 43 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Permit Number                           198900 non-null  str
 1   Permit Type                             198900 non-null  int64
 2   Permit Type Definition                  198900 non-null  str
 3   Permit Creation Date                    198900 non-null  str
 4   Block                                   198900 non-null  str
 5   Lot                                     198900 non-null  str
 6   Street Number                           198900 non-null  int64
 7   Street Number Suffix                    2216 non-null    str
 8   Street Name                             198900 non-null  str
 9   Street Suffix                           196132 non-null  str
 10  Unit                                    29479 non-null   float64
 11  Unit Suffix                             1961 non-null    str
 12  Description                             198610 non-null  str
 13  Current Status                          198900 non-null  str
 14  Current Status Date                     198900 non-null  str
 15  Filed Date                              198900 non-null  str
 16  Issued Date                             183960 non-null  str
 17  Completed Date                          97191 non-null   str
 18  First Construction Document Date        183954 non-null  str
 19  Structural Notification                 6922 non-null    str
 20  Number of Existing Stories              156116 non-null  float64
 21  Number of Proposed Stories              156032 non-null  float64
 22  Voluntary Soft-Story Retrofit           35 non-null      str
 23  Fire Only Permit                        18827 non-null   str
 24  Permit Expiration Date                  147020 non-null  str
 25  Estimated Cost                          160834 non-null  float64
 26  Revised Cost                            192834 non-null  float64
 27  Existing Use                            157786 non-null  str
 28  Existing Units                          147362 non-null  float64
 29  Proposed Use                            156461 non-null  str
 30  Proposed Units                          147989 non-null  float64
 31  Plansets                                161591 non-null  float64
 32  TIDF Compliance                         2 non-null       str
 33  Existing Construction Type              155534 non-null  float64
 34  Existing Construction Type Description  155534 non-null  str
 35  Proposed Construction Type              155738 non-null  float64
 36  Proposed Construction Type Description  155738 non-null  str
 37  Site Permit                             5359 non-null    str
 38  Supervisor District                     197183 non-null  float64
 39  Neighborhoods - Analysis Boundaries     197175 non-null  str
 40  Zipcode                                 197184 non-null  float64
 41  Location                                197200 non-null  str
 42  Record ID                               198900 non-null  int64
dtypes: float64(12), int64(3), str(28)
memory usage: 125.5 MB
None

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

In [297]:
missing_count = df.isnull().sum()

missing_percent = (
    df.isnull().sum() / len(df)
) * 100

missing_report = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing %": missing_percent
})

missing_report = missing_report.sort_values(
    "Missing %",
    ascending=False
)

print(missing_report)

                                        Missing Count  Missing %
TIDF Compliance                                198898  99.998994
Voluntary Soft-Story Retrofit                  198865  99.982403
Unit Suffix                                    196939  99.014077
Street Number Suffix                           196684  98.885872
Site Permit                                    193541  97.305681
Structural Notification                        191978  96.519859
Fire Only Permit                               180073  90.534439
Unit                                           169421  85.178984
Completed Date                                 101709  51.135747
Permit Expiration Date                          51880  26.083459
Existing Units                                  51538  25.911513
Proposed Units                                  50911  25.596280
Existing Construction Type                      43366  21.802916
Existing Construction Type Description          43366  21.802916
Proposed Construction Type Description          43162  21.700352
Proposed Construction Type                      43162  21.700352
Number of Proposed Stories                      42868  21.552539
Number of Existing Stories                      42784  21.510307
Proposed Use                                    42439  21.336853
Existing Use                                    41114  20.670689
Estimated Cost                                  38066  19.138260
Plansets                                        37309  18.757667
First Construction Document Date                14946   7.514329
Issued Date                                     14940   7.511312
Revised Cost                                     6066   3.049774
Street Suffix                                    2768   1.391654
Neighborhoods - Analysis Boundaries              1725   0.867270
Supervisor District                              1717   0.863248
Zipcode                                          1716   0.862745
Location                                         1700   0.854701
Description                                       290   0.145802
Permit Creation Date                                0   0.000000
Permit Number                                       0   0.000000
Permit Type                                         0   0.000000
Permit Type Definition                              0   0.000000
Street Name                                         0   0.000000
Block                                               0   0.000000
Lot                                                 0   0.000000
Street Number                                       0   0.000000
Current Status Date                                 0   0.000000
Current Status                                      0   0.000000
Filed Date                                          0   0.000000
Record ID                                           0   0.000000

In [298]:
df['TIDF Compliance'].dropna().head()

37633     Y
101903    P
Name: TIDF Compliance, dtype: str

In [299]:
df["Voluntary Soft-Story Retrofit"].value_counts(dropna=False)

Voluntary Soft-Story Retrofit
NaN    198865
Y          35
Name: count, dtype: int64

In [300]:
df["Site Permit"].value_counts(dropna=False)

Site Permit
NaN    193541
Y        5359
Name: count, dtype: int64

In [301]:
df[df['Structural Notification'].notna()]["Structural Notification"]

89        Y
100       Y
256       Y
378       Y
380       Y
         ..
198672    Y
198722    Y
198827    Y
198828    Y
198851    Y
Name: Structural Notification, Length: 6922, dtype: str

In [302]:
df["Structural Notification"].unique()

<ArrowStringArray>
[nan, 'Y']
Length: 2, dtype: str

In [303]:
# 1. Define the collection of values you want to search for
target_strings = ['Y', 'No', 'yes', 'no']

# 2. Iterate through every column name in the DataFrame
for column_name in df.columns:
    
    # 3. Check if any row value matches the target strings list
    has_target_value = df[column_name].isin(target_strings).any()
    
    # 4. Print the column name if the condition evaluates to True
    if has_target_value:
        print(f"Target values found in column: {column_name}")

Target values found in column: Street Suffix
Target values found in column: Unit Suffix
Target values found in column: Structural Notification
Target values found in column: Voluntary Soft-Story Retrofit
Target values found in column: Fire Only Permit
Target values found in column: TIDF Compliance
Target values found in column: Site Permit

In [304]:
# 1. Define the specific columns to investigate
target_columns = [
    'Street Suffix', 'Unit Suffix', 'Structural Notification', 
    'Voluntary Soft-Story Retrofit', 'Fire Only Permit', 
    'TIDF Compliance', 'Site Permit'
]

# 2. Establish the array of elements you want to ignore
ignore_values = ['Y', 'No', 'yes', 'no', 'Naa']

for col in target_columns:
    # 3. Build a condition to find values NOT in your ignore list AND NOT missing
    is_not_ignored = ~df[col].isin(ignore_values)
    is_not_missing = ~df[col].isna()
    
    # Combine both conditions using the bitwise AND operator
    unexpected_mask = is_not_ignored & is_not_missing
    
    # 4. Filter the dataframe and pull out only the remaining unique values
    unique_extras = df.loc[unexpected_mask, col].unique()
    
    print(f"Column [{col}] contains these unexpected values: {unique_extras}")

Column [Street Suffix] contains these unexpected values: <ArrowStringArray>
['St', 'Av', 'Tr', 'Ct', 'Bl', 'Wy', 'Dr', 'Rd', 'Cr', 'Pl', 'Ln', 'Hy', 'Pk',
 'Al', 'Pz', 'Wk', 'Rw', 'So', 'Sw', 'Hl']
Length: 20, dtype: str
Column [Unit Suffix] contains these unexpected values: <ArrowStringArray>
[         'A',          'D',     'BLDG 1',          'C',          'B',
          'E',      'FRONT',          'F',      'COMML',        'HOA',
 ...
   'Parcel D',   'Parcel B',   'Parcel C',    'COMML 1',         'D4',
   'PARCEL A',         'M1', 'STUDIO/TEC',       'W122',      'U-PH3']
Length: 163, dtype: str
Column [Structural Notification] contains these unexpected values: <ArrowStringArray>
[]
Length: 0, dtype: str
Column [Voluntary Soft-Story Retrofit] contains these unexpected values: <ArrowStringArray>
[]
Length: 0, dtype: str
Column [Fire Only Permit] contains these unexpected values: <ArrowStringArray>
[]
Length: 0, dtype: str
Column [TIDF Compliance] contains these unexpected values: <ArrowStringArray>
['P']
Length: 1, dtype: str
Column [Site Permit] contains these unexpected values: <ArrowStringArray>
[]
Length: 0, dtype: str

In [305]:

for col in [
    "Current Status",
    "Fire Only Permit",
    "Site Permit",
    "Structural Notification",
    "Voluntary Soft-Story Retrofit",
    "TIDF Compliance"
]:

    print(df[col].value_counts(dropna=False).head(20))

df.duplicated().sum()

df.dtypes

Current Status
complete       97077
issued         83559
filed          12043
withdrawn       1754
cancelled       1536
expired         1370
approved         733
reinstated       563
suspend          193
revoked           50
plancheck         16
appeal             2
disapproved        2
incomplete         2
Name: count, dtype: int64
Fire Only Permit
NaN    180073
Y       18827
Name: count, dtype: int64
Site Permit
NaN    193541
Y        5359
Name: count, dtype: int64

Structural Notification
NaN    191978
Y        6922
Name: count, dtype: int64
Voluntary Soft-Story Retrofit
NaN    198865
Y          35
Name: count, dtype: int64
TIDF Compliance
NaN    198898
Y           1
P           1
Name: count, dtype: int64

Permit Number                                 str
Permit Type                                 int64
Permit Type Definition                        str
Permit Creation Date                          str
Block                                         str
Lot                                           str
Street Number                               int64
Street Number Suffix                          str
Street Name                                   str
Street Suffix                                 str
Unit                                      float64
Unit Suffix                                   str
Description                                   str
Current Status                                str
Current Status Date                           str
Filed Date                                    str
Issued Date                                   str
Completed Date                                str
First Construction Document Date              str
Structural Notification                       str
Number of Existing Stories                float64
Number of Proposed Stories                float64
Voluntary Soft-Story Retrofit                 str
Fire Only Permit                              str
Permit Expiration Date                        str
Estimated Cost                            float64
Revised Cost                              float64
Existing Use                                  str
Existing Units                            float64
Proposed Use                                  str
Proposed Units                            float64
Plansets                                  float64
TIDF Compliance                               str
Existing Construction Type                float64
Existing Construction Type Description        str
Proposed Construction Type                float64
Proposed Construction Type Description        str
Site Permit                                   str
Supervisor District                       float64
Neighborhoods - Analysis Boundaries           str
Zipcode                                   float64
Location                                      str
Record ID                                   int64
dtype: object

In [306]:
# Pass the list of high-missingness columns to drop them at once
columns_to_drop = [
    'TIDF Compliance', 
    'Structural Notification', 
    'Voluntary Soft-Story Retrofit', 
    'Site Permit'
]

df.drop(columns=columns_to_drop, inplace=True)

# Verify the changes by checking the new shape
print(f"New shape after dropping: {df.shape}")

New shape after dropping: (198900, 39)

In [307]:
# Count the total number of rows that are 100% identical copies
duplicate_count = df.duplicated().sum()
print(f"Total duplicate rows: {duplicate_count}")

Total duplicate rows: 0

In [308]:
# 1. Fill missing values first with a temporary numerical anchor
df['Unit_Clean'] = df['Unit'].fillna(-1)

# 2. Cast the float column down to an integer to drop scientific formatting
df['Unit_Clean'] = df['Unit_Clean'].astype(int)

# 3. Convert the integer elements to clean text strings
df['Unit_Clean'] = df['Unit_Clean'].astype(str)

# 4. Replace the temporary anchor '-1' with a clean, empty string
df['Unit_Clean'] = df['Unit_Clean'].replace('-1', '')

# 5. Print unique values to verify the formatting fix
print(df['Unit_Clean'].unique()[:15])

<ArrowStringArray>
[    '',    '0',  '301',    '1',  '201', '1007',  '401',  '510',  '726',
 '3412',   '14',  '102',  '209',  '307',  '501']
Length: 15, dtype: str

In [309]:
print(df.shape)
print(df.columns)
print(df.head())
print(df.info())

(198900, 40)
Index(['Permit Number', 'Permit Type', 'Permit Type Definition',
       'Permit Creation Date', 'Block', 'Lot', 'Street Number',
       'Street Number Suffix', 'Street Name', 'Street Suffix', 'Unit',
       'Unit Suffix', 'Description', 'Current Status', 'Current Status Date',
       'Filed Date', 'Issued Date', 'Completed Date',
       'First Construction Document Date', 'Number of Existing Stories',
       'Number of Proposed Stories', 'Fire Only Permit',
       'Permit Expiration Date', 'Estimated Cost', 'Revised Cost',
       'Existing Use', 'Existing Units', 'Proposed Use', 'Proposed Units',
       'Plansets', 'Existing Construction Type',
       'Existing Construction Type Description', 'Proposed Construction Type',
       'Proposed Construction Type Description', 'Supervisor District',
       'Neighborhoods - Analysis Boundaries', 'Zipcode', 'Location',
       'Record ID', 'Unit_Clean'],
      dtype='str')
  Permit Number  Permit Type            Permit Type Definition  \
0  201505065519            4                      sign - erect
1  201604195146            4                      sign - erect
2  201605278609            3  additions alterations or repairs
3  201611072166            8            otc alterations permit
4  201611283529            6                       demolitions

  Permit Creation Date Block  Lot  Street Number Street Number Suffix  \
0           05/06/2015  0326  023            140                  NaN
1           04/19/2016  0306  007            440                  NaN
2           05/27/2016  0595  203           1647                  NaN
3           11/07/2016  0156  011           1230                  NaN
4           11/28/2016  0342  001            950                  NaN

  Street Name Street Suffix  ...  Existing Construction Type  \
0       Ellis            St  ...                         3.0
1       Geary            St  ...                         3.0
2     Pacific            Av  ...                         1.0
3     Pacific            Av  ...                         5.0
4      Market            St  ...                         3.0

  Existing Construction Type Description Proposed Construction Type  \
0                          constr type 3                        NaN
1                          constr type 3                        NaN
2                          constr type 1                        1.0
3                         wood frame (5)                        5.0
4                          constr type 3                        NaN

  Proposed Construction Type Description Supervisor District  \
0                                    NaN                 3.0
1                                    NaN                 3.0
2                          constr type 1                 3.0
3                         wood frame (5)                 3.0
4                                    NaN                 6.0

  Neighborhoods - Analysis Boundaries  Zipcode  \
0                          Tenderloin  94102.0
1                          Tenderloin  94102.0
2                        Russian Hill  94109.0
3                            Nob Hill  94109.0
4                          Tenderloin  94102.0

                                    Location      Record ID  Unit_Clean
0  (37.785719256680785, -122.40852313194863)  1380611233945
1   (37.78733980600732, -122.41063199757738)  1420164406718           0
2    (37.7946573324287, -122.42232562979227)  1424856504716
3   (37.79595867909168, -122.41557405519474)  1443574295566           0
4   (37.78315261897309, -122.40950883997789)   144548169992

[5 rows x 40 columns]
<class 'pandas.DataFrame'>
RangeIndex: 198900 entries, 0 to 198899
Data columns (total 40 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Permit Number                           198900 non-null  str
 1   Permit Type                             198900 non-null  int64
 2   Permit Type Definition                  198900 non-null  str
 3   Permit Creation Date                    198900 non-null  str
 4   Block                                   198900 non-null  str
 5   Lot                                     198900 non-null  str
 6   Street Number                           198900 non-null  int64
 7   Street Number Suffix                    2216 non-null    str
 8   Street Name                             198900 non-null  str
 9   Street Suffix                           196132 non-null  str
 10  Unit                                    29479 non-null   float64
 11  Unit Suffix                             1961 non-null    str
 12  Description                             198610 non-null  str
 13  Current Status                          198900 non-null  str
 14  Current Status Date                     198900 non-null  str
 15  Filed Date                              198900 non-null  str
 16  Issued Date                             183960 non-null  str
 17  Completed Date                          97191 non-null   str
 18  First Construction Document Date        183954 non-null  str
 19  Number of Existing Stories              156116 non-null  float64
 20  Number of Proposed Stories              156032 non-null  float64
 21  Fire Only Permit                        18827 non-null   str
 22  Permit Expiration Date                  147020 non-null  str
 23  Estimated Cost                          160834 non-null  float64
 24  Revised Cost                            192834 non-null  float64
 25  Existing Use                            157786 non-null  str
 26  Existing Units                          147362 non-null  float64
 27  Proposed Use                            156461 non-null  str
 28  Proposed Units                          147989 non-null  float64
 29  Plansets                                161591 non-null  float64
 30  Existing Construction Type              155534 non-null  float64
 31  Existing Construction Type Description  155534 non-null  str
 32  Proposed Construction Type              155738 non-null  float64
 33  Proposed Construction Type Description  155738 non-null  str
 34  Supervisor District                     197183 non-null  float64
 35  Neighborhoods - Analysis Boundaries     197175 non-null  str
 36  Zipcode                                 197184 non-null  float64
 37  Location                                197200 non-null  str
 38  Record ID                               198900 non-null  int64
 39  Unit_Clean                              198900 non-null  str
dtypes: float64(12), int64(3), str(25)
memory usage: 120.9 MB
None

In [310]:
df.head(50)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID,Unit_Clean
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945,
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718,0
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716,
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566,0
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992,
5,201706149344,8,otc alterations permit,06/14/2017,4105,009,800,NaN,Indiana,St,...,1.0,constr type 1,1.0,constr type 1,10.0,Potrero Hill,94107.0,"(37.75922331346539, -122.39170402628598)",1466911170855,
6,201706300814,8,otc alterations permit,06/30/2017,1739,020,1291,NaN,11th,Av,...,5.0,wood frame (5),5.0,wood frame (5),5.0,Inner Sunset,94122.0,"(37.764145640138565, -122.46875112470363)",1468970403692,0
7,M803667,8,otc alterations permit,06/30/2017,4789,014,1465,NaN,Revere,Av,...,NaN,NaN,NaN,NaN,10.0,Bayview Hunters Point,94124.0,"(37.73005099023611, -122.38784938916618)",1469035175050,
8,M804227,8,otc alterations permit,07/05/2017,1212,054,2094,NaN,Fell,St,...,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.772393498502595, -122.45231466824669)",1469198253772,
9,M804767,8,otc alterations permit,07/06/2017,1259,016,89,NaN,Alpine,Tr,...,NaN,NaN,NaN,NaN,8.0,Haight Ashbury,94117.0,"(37.7691724293766, -122.43734859051908)",146932394171,
10,M805287,8,otc alterations permit,07/06/2017,3541,001,106,NaN,Sanchez,St,...,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114.0,"(37.767349757757145, -122.43140682973024)",1469445246849,
11,M805907,8,otc alterations permit,07/07/2017,0829,021,675,NaN,Fell,St,...,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94102.0,"(37.774914087334544, -122.42886839796792)",146961582526,
12,M806447,8,otc alterations permit,07/10/2017,6537,023,4082,NaN,25th,St,...,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114.0,"(37.75006779619502, -122.43127350268124)",1469781206718,
13,201707252846,8,otc alterations permit,07/25/2017,6589,002R,681,NaN,27th,St,...,5.0,wood frame (5),5.0,wood frame (5),8.0,Noe Valley,94131.0,"(37.7462205625642, -122.4353484860549)",1471799208305,
14,M813729,8,otc alterations permit,07/26/2017,1049,027,2761,NaN,Pine,St,...,NaN,NaN,NaN,NaN,2.0,Pacific Heights,94115.0,"(37.78676200041077, -122.44124093333335)",147203988249,
15,M813907,8,otc alterations permit,07/27/2017,0243,043,840,NaN,Powell,St,...,NaN,NaN,NaN,NaN,3.0,Chinatown,94108.0,"(37.7926690651263, -122.40883941791454)",147208763456,301
16,M813967,8,otc alterations permit,07/27/2017,0268,008,220,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,3.0,Financial District/South Beach,94104.0,"(37.79130641988351, -122.40198579459195)",147211866168,
17,M814148,8,otc alterations permit,07/27/2017,3621,097,3707,NaN,21st,St,...,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114.0,"(37.75607840165479, -122.43041143390109)",1472184412108,0
18,201707283165,8,otc alterations permit,07/28/2017,0472,042,1307,NaN,Bay,St,...,5.0,wood frame (5),5.0,wood frame (5),2.0,Marina,94123.0,"(37.8035183252307, -122.42863180996076)",1472277302360,1
19,M814368,8,otc alterations permit,07/28/2017,2659,001,263,NaN,Corbett,Av,...,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114.0,"(37.761092365437214, -122.44402154957145)",1472295408612,0
20,M814967,8,otc alterations permit,07/31/2017,1176,068,1624,NaN,Fulton,St,...,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77640228859421, -122.44361679686382)",1472619503582,
21,201708013476,8,otc alterations permit,08/01/2017,6529,010,3410,NaN,26th,St,...,5.0,wood frame (5),5.0,wood frame (5),9.0,Mission,94110.0,"(37.74914175355125, -122.41849211166853)",1472727381751,
22,201708013544,3,additions alterations or repairs,08/01/2017,0074,043,2150,NaN,Taylor,St,...,5.0,wood frame (5),5.0,wood frame (5),3.0,Russian Hill,94133.0,"(37.802405951667645, -122.41446286561653)",147281357792,
23,M816927,8,otc alterations permit,08/07/2017,0941,012,2824,NaN,Filbert,St,...,NaN,NaN,NaN,NaN,2.0,Marina,94123.0,"(37.79697456740493, -122.44615769723546)",147359384812,
24,201708084249,8,otc alterations permit,08/08/2017,0542,039,1,NaN,Charlton,Ct,...,5.0,wood frame (5),5.0,wood frame (5),2.0,Marina,94123.0,"(37.79739093461306, -122.43127133823367)",1473796372030,
25,201708165014,8,otc alterations permit,08/16/2017,1824,006,1435,NaN,29th,Av,...,5.0,wood frame (5),5.0,wood frame (5),4.0,Sunset/Parkside,94122.0,"(37.76052279949518, -122.4879889739165)",1474841115935,
26,M820728,8,otc alterations permit,08/18/2017,1449,006,331,NaN,17th,Av,...,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94121.0,"(37.78177022745135, -122.47658979438802)",1475223100163,
27,M821207,8,otc alterations permit,08/21/2017,1193,024,120,NaN,Shrader,St,...,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77371007080848, -122.45243180846707)",147537591942,
28,M821268,8,otc alterations permit,08/21/2017,1851,012,1512,NaN,06th,Av,...,NaN,NaN,NaN,NaN,7.0,Inner Sunset,94122.0,"(37.760252335082875, -122.4625393396095)",1475405117215,
29,M821847,8,otc alterations permit,08/22/2017,0326,001,165,NaN,Powell,St,...,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78625524960107, -122.40834431815433)",1475605447747,
30,M822307,8,otc alterations permit,08/23/2017,0182,004,1441,NaN,Taylor,St,...,NaN,NaN,NaN,NaN,3.0,Nob Hill,94133.0,"(37.79566333315149, -122.41363462406336)",1475757406474,0
31,M822487,8,otc alterations permit,08/23/2017,3580,017,3830,NaN,18th,St,...,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114.0,"(37.761512899115466, -122.42911964946909)",1475795422554,0
32,M822707,8,otc alterations permit,08/23/2017,3610,041,563,NaN,Capp,St,...,NaN,NaN,NaN,NaN,9.0,Mission,94110.0,"(37.75771026684177, -122.4175528755785)",1475838161926,
33,201708245836,3,additions alterations or repairs,08/24/2017,3749,047,76,NaN,Lansing,St,...,5.0,wood frame (5),5.0,wood frame (5),6.0,Financial District/South Beach,94105.0,"(37.78595425737664, -122.39444130117158)",1476032285416,
34,M823847,8,otc alterations permit,08/25/2017,3545,018A,1810,NaN,15th,St,...,NaN,NaN,NaN,NaN,8.0,Mission,94103.0,"(37.766508011617525, -122.42470825254468)",1476234157693,
35,M824007,8,otc alterations permit,08/25/2017,0749,006A,1445,NaN,Eddy,St,...,NaN,NaN,NaN,NaN,5.0,Western Addition,94115.0,"(37.7813061748427, -122.43142154292566)",147627380882,
36,M824127,8,otc alterations permit,08/28/2017,6551,023,1383,NaN,Church,St,...,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114.0,"(37.748779856735744, -122.42683572581998)",1476358207225,
37,M824927,8,otc alterations permit,08/29/2017,6597,024,681,NaN,San Jose,Av,...,NaN,NaN,NaN,NaN,8.0,Bernal Heights,94110.0,"(37.74446179156465, -122.42217241874201)",1476706208668,
38,M825267,8,otc alterations permit,08/29/2017,1572,017,606,NaN,30th,Av,...,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94121.0,"(37.77767213358907, -122.48966493609916)",1476720105056,
39,M828787,8,otc alterations permit,09/07/2017,0177,022,655,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,3.0,Chinatown,94133.0,"(37.79673343870443, -122.40610115140781)",1477872407335,0
40,M829567,8,otc alterations permit,09/08/2017,0490,002,3325,NaN,Steiner,St,...,NaN,NaN,NaN,NaN,2.0,Marina,94123.0,"(37.80002156448977, -122.43806594677513)",147813971761,
41,M832207,8,otc alterations permit,09/15/2017,1609,021F,700,NaN,36th,Av,...,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94121.0,"(37.77554028396788, -122.49601102992328)",1479528106617,
42,201709158571,8,otc alterations permit,09/15/2017,1429,010,249,NaN,04th,Av,...,5.0,wood frame (5),5.0,wood frame (5),1.0,Inner Richmond,94118.0,"(37.7839252036892, -122.46267353170244)",1479741242383,
43,M833229,8,otc alterations permit,09/19/2017,0605,028,2379,NaN,Jackson,St,...,NaN,NaN,NaN,NaN,2.0,Pacific Heights,94115.0,"(37.792266300903314, -122.4340191358936)",1480161420671,1
44,M834107,8,otc alterations permit,09/21/2017,7151,014,247,NaN,Saint Charles,Av,...,NaN,NaN,NaN,NaN,7.0,Oceanview/Merced/Ingleside,94132.0,"(37.70944796125683, -122.4690186732598)",1480578483312,0
45,M836287,8,otc alterations permit,09/27/2017,0540,002,2843,NaN,Webster,St,...,NaN,NaN,NaN,NaN,2.0,Marina,94123.0,"(37.79686934709798, -122.43412132328224)",1481221235128,
46,M836847,8,otc alterations permit,09/28/2017,0959,029,2615,NaN,Divisadero,St,...,NaN,NaN,NaN,NaN,2.0,Pacific Heights,94123.0,"(37.79391508281414, -122.44195481827035)",1481434475430,
47,M839427,8,otc alterations permit,10/04/2017,6780,034,252,NaN,Cotter,St,...,NaN,NaN,NaN,NaN,11.0,Outer Mission,94112.0,"(37.729885737657085, -122.43669590253097)",1482203213002,
48,201710110928,8,otc alterations permit,10/11/2017,5934,020,938,NaN,Felton,St,...,5.0,wood frame (5),5.0,wood frame (5),9.0,Portola,94134.0,"(37.72775517946509, -122.41419227409298)",1482932191681,
49,M842668,8,otc alterations permit,10/11/2017,1558,009,535,NaN,15th,Av,...,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94118.0,"(37.777944902487455, -122.47412411653805)",1482945104295,

In [311]:
# Check for duplicate column names
column_counts = pd.Series(df.columns).value_counts()
duplicate_columns = column_counts[column_counts > 1]

if not duplicate_columns.empty:
    print("Duplicate columns found:\n", duplicate_columns)
else:
    print("No duplicate column names found.")

No duplicate column names found.

In [312]:
# Define target columns for multi-column inspection
target_columns = ["Permit Number", "Permit Type", "Permit Type Definition", "Permit Creation Date"]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Permit Number ---
<ArrowStringArray>
['201505065519', '201604195146', '201605278609', '201611072166',
 '201611283529', '201706149344', '201706300814',      'M803667',
      'M804227',      'M804767']
Length: 10, dtype: str


--- Unique samples for Permit Type ---
[4 3 8 6 7 1 5 2]


--- Unique samples for Permit Type Definition ---
<ArrowStringArray>
[                       'sign - erect',    'additions alterations or repairs',
              'otc alterations permit',                         'demolitions',
                'wall or painted sign',                    'new construction',
 'grade or quarry or fill or excavate',         'new construction wood frame']
Length: 8, dtype: str


--- Unique samples for Permit Creation Date ---
<ArrowStringArray>
['05/06/2015', '04/19/2016', '05/27/2016', '11/07/2016', '11/28/2016',
 '06/14/2017', '06/30/2017', '07/05/2017', '07/06/2017', '07/07/2017']
Length: 10, dtype: str

In [313]:
# Define target columns for multi-column inspection
target_columns = ["Permit Number", "Permit Type", "Permit Type Definition", "Permit Creation Date"]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Permit Number ---

<ArrowStringArray>
['201505065519', '201604195146', '201605278609', '201611072166',
 '201611283529', '201706149344', '201706300814',      'M803667',
      'M804227',      'M804767']
Length: 10, dtype: str


--- Unique samples for Permit Type ---
[4 3 8 6 7 1 5 2]


--- Unique samples for Permit Type Definition ---
<ArrowStringArray>
[                       'sign - erect',    'additions alterations or repairs',
              'otc alterations permit',                         'demolitions',
                'wall or painted sign',                    'new construction',
 'grade or quarry or fill or excavate',         'new construction wood frame']
Length: 8, dtype: str


--- Unique samples for Permit Creation Date ---
<ArrowStringArray>
['05/06/2015', '04/19/2016', '05/27/2016', '11/07/2016', '11/28/2016',
 '06/14/2017', '06/30/2017', '07/05/2017', '07/06/2017', '07/07/2017']
Length: 10, dtype: str

In [314]:
# Define target columns for multi-column inspection
target_columns = ["Block", "Lot", "Street Number", "Street Number Suffix" ]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Block ---
<ArrowStringArray>
['0326', '0306', '0595', '0156', '0342', '4105', '1739', '4789', '1212',
 '1259']
Length: 10, dtype: str


--- Unique samples for Lot ---
<ArrowStringArray>
['023', '007', '203', '011', '001', '009', '020', '014', '054', '016']
Length: 10, dtype: str


--- Unique samples for Street Number ---
[ 140  440 1647 1230  950  800 1291 1465 2094   89]


--- Unique samples for Street Number Suffix ---
<ArrowStringArray>
['A', 'C', 'V', 'B', 'F', 'R', 'D', '0', 'E', 'P']
Length: 10, dtype: str

In [315]:
# Define target columns for multi-column inspection
target_columns = ["Street Name", "Street Suffix", "Unit", "Unit Suffix" ]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Street Name ---
<ArrowStringArray>
[  'Ellis',   'Geary', 'Pacific',  'Market', 'Indiana',    '11th',  'Revere',
    'Fell',  'Alpine', 'Sanchez']
Length: 10, dtype: str


--- Unique samples for Street Suffix ---
<ArrowStringArray>
['St', 'Av', 'Tr', 'Ct', 'Bl', 'Wy', 'Dr', 'Rd', 'Cr', 'Pl']
Length: 10, dtype: str


--- Unique samples for Unit ---
[0.000e+00 3.010e+02 1.000e+00 2.010e+02 1.007e+03 4.010e+02 5.100e+02
 7.260e+02 3.412e+03 1.400e+01]


--- Unique samples for Unit Suffix ---
<ArrowStringArray>
['A', 'D', 'BLDG 1', 'C', 'B', 'E', 'FRONT', 'F', 'COMML', 'HOA']
Length: 10, dtype: str

In [316]:
# Define target columns for multi-column inspection
target_columns = ["Description", "Current Status", "Current Status Date", "Filed Date"]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Description ---
<ArrowStringArray>
['ground fl facade: to erect illuminated, electric, wall, single faced sign. n/a for maher ordinance 155-13.',
                                                                    'remove (e) awning and associated signs.',
                                                                            'installation of separating wall',
                                                                   'repair dryrot & stucco at front of bldg.',
                                                         'demolish retail/office/commercial 3-story building',
                                                                                                  'evac maps',
                                                                                                 're-roofing',
                                                                                                'streetspace',
                                                                                        'street space permit',
                                                                                               'street space']
Length: 10, dtype: str


--- Unique samples for Current Status ---
<ArrowStringArray>
[   'expired',     'issued',  'withdrawn',   'complete',      'filed',
   'approved', 'reinstated',  'cancelled',     'appeal',    'suspend']
Length: 10, dtype: str


--- Unique samples for Current Status Date ---
<ArrowStringArray>
['12/21/2017', '08/03/2017', '09/26/2017', '07/24/2017', '12/01/2017',
 '07/06/2017', '07/12/2017', '06/30/2017', '07/05/2017', '07/07/2017']
Length: 10, dtype: str


--- Unique samples for Filed Date ---
<ArrowStringArray>
['05/06/2015', '04/19/2016', '05/27/2016', '11/07/2016', '11/28/2016',
 '06/14/2017', '06/30/2017', '07/05/2017', '07/06/2017', '07/07/2017']
Length: 10, dtype: str

In [317]:
# Target columns for inspection
target_columns = ["Issued Date", "Completed Date", "First Construction Document Date", "Number of Existing Stories"]

# Loop safely by checking if the column exists first
for col in target_columns:
    if col in df.columns:
        print(f"--- Unique samples for {col} ---")
        print(df[col].dropna().unique()[:10])
        print("\n")
    else:
        print(f"!!! Column not found in DataFrame: '{col}' !!!\n")

--- Unique samples for Issued Date ---
<ArrowStringArray>
['11/09/2015', '08/03/2017', '07/18/2017', '12/01/2017', '07/06/2017',
 '06/30/2017', '07/05/2017', '07/07/2017', '07/10/2017', '07/26/2017']
Length: 10, dtype: str


--- Unique samples for Completed Date ---
<ArrowStringArray>
['07/24/2017', '07/12/2017', '10/31/2017', '09/08/2017', '10/04/2017',
 '10/13/2017', '10/10/2017', '09/28/2017', '01/19/2018', '09/22/2017']
Length: 10, dtype: str


--- Unique samples for First Construction Document Date ---

<ArrowStringArray>
['11/09/2015', '08/03/2017', '07/18/2017', '11/20/2017', '07/06/2017',
 '06/30/2017', '07/05/2017', '07/07/2017', '07/10/2017', '07/26/2017']
Length: 10, dtype: str


--- Unique samples for Number of Existing Stories ---
[ 6.  7.  2.  3.  5.  4.  1. 15. 23. 11.]

In [318]:
# Define target columns for multi-column inspection
target_columns = ["Number of Proposed Stories", "Fire Only Permit", "Permit Expiration Date", "Estimated Cost" ]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Number of Proposed Stories ---
[ 6.  2.  5.  3.  4.  1. 23. 13. 22. 21.]


--- Unique samples for Fire Only Permit ---
<ArrowStringArray>
['Y']
Length: 1, dtype: str


--- Unique samples for Permit Expiration Date ---
<ArrowStringArray>
['11/03/2016', '12/03/2017', '07/13/2018', '12/01/2018', '07/01/2018',
 '06/25/2018', '08/08/2018', '02/16/2018', '04/11/2018', '05/27/2018']
Length: 10, dtype: str


--- Unique samples for Estimated Cost ---
[4.000e+03 1.000e+00 2.000e+04 2.000e+03 1.000e+05 1.200e+04 3.000e+04
 7.500e+04 6.465e+04 7.000e+03]

In [319]:
# Define target columns for multi-column inspection
target_columns = ["Revised Cost", "Existing Use", "Existing Units", "Proposed Use"]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Revised Cost ---
[4.000e+03 5.000e+02 2.000e+03 1.000e+05 1.200e+04 0.000e+00 1.000e+00
 6.465e+04 7.000e+03 7.300e+04]


--- Unique samples for Existing Use ---
<ArrowStringArray>
[ 'tourist hotel/motel',         'retail sales',    '1 family dwelling',
           'apartments',    '2 family dwelling',               'church',
         'storage shed',               'office',           'vacant lot',
 'food/beverage hndlng']
Length: 10, dtype: str


--- Unique samples for Existing Units ---
[143.  39.   1. 326.   5.   6.   2.   9.   3.   8.]


--- Unique samples for Proposed Use ---
<ArrowStringArray>
[       'retail sales',   '1 family dwelling',          'apartments',
   '2 family dwelling',              'church',          'vacant lot',
              'office', 'tourist hotel/motel',              'school',
 'filling/service stn']
Length: 10, dtype: str

In [320]:
# Define target columns for multi-column inspection
target_columns = ["Proposed Units", "Plansets", "Existing Construction Type", "Existing Construction Type Description" ]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Proposed Units ---
[ 39.   1. 326.   5.   6.   2.   9.   3.   8.  74.]


--- Unique samples for Plansets ---
[2.e+00 0.e+00 6.e+00 4.e+00 3.e+00 2.e+01 9.e+03 1.e+00]


--- Unique samples for Existing Construction Type ---
[3. 1. 5. 2. 4.]


--- Unique samples for Existing Construction Type Description ---
<ArrowStringArray>
[ 'constr type 3',  'constr type 1', 'wood frame (5)',  'constr type 2',
  'constr type 4']
Length: 5, dtype: str

In [321]:
# Define target columns for multi-column inspection
target_columns = ["Proposed Construction Type", "Proposed Construction Type Description", "Supervisor District", "Neighborhoods - Analysis Boundaries"]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Proposed Construction Type ---
[1. 5. 3. 4. 2.]


--- Unique samples for Proposed Construction Type Description ---
<ArrowStringArray>
[ 'constr type 1', 'wood frame (5)',  'constr type 3',  'constr type 4',
  'constr type 2']
Length: 5, dtype: str


--- Unique samples for Supervisor District ---
[ 3.  6. 10.  5.  8.  2.  9.  4.  1.  7.]


--- Unique samples for Neighborhoods - Analysis Boundaries ---
<ArrowStringArray>
[           'Tenderloin',          'Russian Hill',              'Nob Hill',
          'Potrero Hill',          'Inner Sunset', 'Bayview Hunters Point',
     'Lone Mountain/USF',        'Haight Ashbury',   'Castro/Upper Market',
          'Hayes Valley']
Length: 10, dtype: str

In [322]:
# Define target columns for multi-column inspection
target_columns = ["Zipcode", "Location", "Record ID", "Unit_Clean"]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Zipcode ---
[94102. 94109. 94107. 94122. 94124. 94117. 94114. 94131. 94115. 94108.]


--- Unique samples for Location ---

<ArrowStringArray>
['(37.785719256680785, -122.40852313194863)',
  '(37.78733980600732, -122.41063199757738)',
   '(37.7946573324287, -122.42232562979227)',
  '(37.79595867909168, -122.41557405519474)',
  '(37.78315261897309, -122.40950883997789)',
  '(37.75922331346539, -122.39170402628598)',
 '(37.764145640138565, -122.46875112470363)',
  '(37.73005099023611, -122.38784938916618)',
 '(37.772393498502595, -122.45231466824669)',
   '(37.7691724293766, -122.43734859051908)']
Length: 10, dtype: str


--- Unique samples for Record ID ---
[1380611233945 1420164406718 1424856504716 1443574295566  144548169992
 1466911170855 1468970403692 1469035175050 1469198253772  146932394171]


--- Unique samples for Unit_Clean ---
<ArrowStringArray>
['', '0', '301', '1', '201', '1007', '401', '510', '726', '3412']
Length: 10, dtype: str

In [323]:
# Convert the formatted as generic object strings explicitly to standard Pandas datetime formats:
date_cols = [
    "Permit Creation Date", "Current Status Date", "Filed Date", 
    "Issued Date", "Completed Date", "First Construction Document Date", 
    "Permit Expiration Date"
]
for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], format="%m/%d/%Y", errors="coerce")

In [324]:
# Text cleanup
df["Description"] = df["Description"].astype(str).str.strip().str.lower()

for col in ["Existing Use", "Proposed Use"]:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.title()

In [325]:
# Text cleanup: astype(str) converts all data points in the column into string formatting to prevent errors from mixed types like integers or missing values. str.strip() removes any accidental leading or trailing spaces from the text boundaries. 
# str.lower() converts all characters in the column to lowercase format. str.title() capitalizes the first letter of every word and forces all other letters to lowercase format.
df["Description"] = df["Description"].astype(str).str.strip().str.lower()

for col in ["Existing Use", "Proposed Use"]:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.title()

In [326]:
int_convert_cols = ["Unit", "Existing Units", "Proposed Units", "Plansets"]
for col in int_convert_cols:
    if col in df.columns:
        # Convert to numeric float first, round or drop decimals, then convert to Int64
        numeric_series = pd.to_numeric(df[col], errors="coerce")
        df[col] = numeric_series.round().astype("Int64")

In [327]:
# Fix Zipcode format: 
if "Zipcode" in df.columns:
    df["Zipcode"] = df["Zipcode"].astype(str).str.split(".").str[0].str.strip()

# Replace empty strings with NaN
if "Unit_Clean" in df.columns:
    df["Unit_Clean"] = df["Unit_Clean"].replace(r"^\s*$", pd.NA, regex=True)

In [328]:
df.head(50)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID,Unit_Clean
0,201505065519,4,sign - erect,2015-05-06,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,3.0,Tenderloin,94102,"(37.785719256680785, -122.40852313194863)",1380611233945,NaN
1,201604195146,4,sign - erect,2016-04-19,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,3.0,Tenderloin,94102,"(37.78733980600732, -122.41063199757738)",1420164406718,0
2,201605278609,3,additions alterations or repairs,2016-05-27,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,3.0,Russian Hill,94109,"(37.7946573324287, -122.42232562979227)",1424856504716,NaN
3,201611072166,8,otc alterations permit,2016-11-07,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),3.0,Nob Hill,94109,"(37.79595867909168, -122.41557405519474)",1443574295566,0
4,201611283529,6,demolitions,2016-11-28,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,6.0,Tenderloin,94102,"(37.78315261897309, -122.40950883997789)",144548169992,NaN
5,201706149344,8,otc alterations permit,2017-06-14,4105,009,800,NaN,Indiana,St,...,1.0,constr type 1,1.0,constr type 1,10.0,Potrero Hill,94107,"(37.75922331346539, -122.39170402628598)",1466911170855,NaN
6,201706300814,8,otc alterations permit,2017-06-30,1739,020,1291,NaN,11th,Av,...,5.0,wood frame (5),5.0,wood frame (5),5.0,Inner Sunset,94122,"(37.764145640138565, -122.46875112470363)",1468970403692,0
7,M803667,8,otc alterations permit,2017-06-30,4789,014,1465,NaN,Revere,Av,...,NaN,NaN,NaN,NaN,10.0,Bayview Hunters Point,94124,"(37.73005099023611, -122.38784938916618)",1469035175050,NaN
8,M804227,8,otc alterations permit,2017-07-05,1212,054,2094,NaN,Fell,St,...,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117,"(37.772393498502595, -122.45231466824669)",1469198253772,NaN
9,M804767,8,otc alterations permit,2017-07-06,1259,016,89,NaN,Alpine,Tr,...,NaN,NaN,NaN,NaN,8.0,Haight Ashbury,94117,"(37.7691724293766, -122.43734859051908)",146932394171,NaN
10,M805287,8,otc alterations permit,2017-07-06,3541,001,106,NaN,Sanchez,St,...,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114,"(37.767349757757145, -122.43140682973024)",1469445246849,NaN
11,M805907,8,otc alterations permit,2017-07-07,0829,021,675,NaN,Fell,St,...,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94102,"(37.774914087334544, -122.42886839796792)",146961582526,NaN
12,M806447,8,otc alterations permit,2017-07-10,6537,023,4082,NaN,25th,St,...,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114,"(37.75006779619502, -122.43127350268124)",1469781206718,NaN
13,201707252846,8,otc alterations permit,2017-07-25,6589,002R,681,NaN,27th,St,...,5.0,wood frame (5),5.0,wood frame (5),8.0,Noe Valley,94131,"(37.7462205625642, -122.4353484860549)",1471799208305,NaN
14,M813729,8,otc alterations permit,2017-07-26,1049,027,2761,NaN,Pine,St,...,NaN,NaN,NaN,NaN,2.0,Pacific Heights,94115,"(37.78676200041077, -122.44124093333335)",147203988249,NaN
15,M813907,8,otc alterations permit,2017-07-27,0243,043,840,NaN,Powell,St,...,NaN,NaN,NaN,NaN,3.0,Chinatown,94108,"(37.7926690651263, -122.40883941791454)",147208763456,301
16,M813967,8,otc alterations permit,2017-07-27,0268,008,220,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,3.0,Financial District/South Beach,94104,"(37.79130641988351, -122.40198579459195)",147211866168,NaN
17,M814148,8,otc alterations permit,2017-07-27,3621,097,3707,NaN,21st,St,...,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114,"(37.75607840165479, -122.43041143390109)",1472184412108,0
18,201707283165,8,otc alterations permit,2017-07-28,0472,042,1307,NaN,Bay,St,...,5.0,wood frame (5),5.0,wood frame (5),2.0,Marina,94123,"(37.8035183252307, -122.42863180996076)",1472277302360,1
19,M814368,8,otc alterations permit,2017-07-28,2659,001,263,NaN,Corbett,Av,...,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114,"(37.761092365437214, -122.44402154957145)",1472295408612,0
20,M814967,8,otc alterations permit,2017-07-31,1176,068,1624,NaN,Fulton,St,...,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117,"(37.77640228859421, -122.44361679686382)",1472619503582,NaN
21,201708013476,8,otc alterations permit,2017-08-01,6529,010,3410,NaN,26th,St,...,5.0,wood frame (5),5.0,wood frame (5),9.0,Mission,94110,"(37.74914175355125, -122.41849211166853)",1472727381751,NaN
22,201708013544,3,additions alterations or repairs,2017-08-01,0074,043,2150,NaN,Taylor,St,...,5.0,wood frame (5),5.0,wood frame (5),3.0,Russian Hill,94133,"(37.802405951667645, -122.41446286561653)",147281357792,NaN
23,M816927,8,otc alterations permit,2017-08-07,0941,012,2824,NaN,Filbert,St,...,NaN,NaN,NaN,NaN,2.0,Marina,94123,"(37.79697456740493, -122.44615769723546)",147359384812,NaN
24,201708084249,8,otc alterations permit,2017-08-08,0542,039,1,NaN,Charlton,Ct,...,5.0,wood frame (5),5.0,wood frame (5),2.0,Marina,94123,"(37.79739093461306, -122.43127133823367)",1473796372030,NaN
25,201708165014,8,otc alterations permit,2017-08-16,1824,006,1435,NaN,29th,Av,...,5.0,wood frame (5),5.0,wood frame (5),4.0,Sunset/Parkside,94122,"(37.76052279949518, -122.4879889739165)",1474841115935,NaN
26,M820728,8,otc alterations permit,2017-08-18,1449,006,331,NaN,17th,Av,...,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94121,"(37.78177022745135, -122.47658979438802)",1475223100163,NaN
27,M821207,8,otc alterations permit,2017-08-21,1193,024,120,NaN,Shrader,St,...,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117,"(37.77371007080848, -122.45243180846707)",147537591942,NaN
28,M821268,8,otc alterations permit,2017-08-21,1851,012,1512,NaN,06th,Av,...,NaN,NaN,NaN,NaN,7.0,Inner Sunset,94122,"(37.760252335082875, -122.4625393396095)",1475405117215,NaN
29,M821847,8,otc alterations permit,2017-08-22,0326,001,165,NaN,Powell,St,...,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102,"(37.78625524960107, -122.40834431815433)",1475605447747,NaN
30,M822307,8,otc alterations permit,2017-08-23,0182,004,1441,NaN,Taylor,St,...,NaN,NaN,NaN,NaN,3.0,Nob Hill,94133,"(37.79566333315149, -122.41363462406336)",1475757406474,0
31,M822487,8,otc alterations permit,2017-08-23,3580,017,3830,NaN,18th,St,...,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114,"(37.761512899115466, -122.42911964946909)",1475795422554,0
32,M822707,8,otc alterations permit,2017-08-23,3610,041,563,NaN,Capp,St,...,NaN,NaN,NaN,NaN,9.0,Mission,94110,"(37.75771026684177, -122.4175528755785)",1475838161926,NaN
33,201708245836,3,additions alterations or repairs,2017-08-24,3749,047,76,NaN,Lansing,St,...,5.0,wood frame (5),5.0,wood frame (5),6.0,Financial District/South Beach,94105,"(37.78595425737664, -122.39444130117158)",1476032285416,NaN
34,M823847,8,otc alterations permit,2017-08-25,3545,018A,1810,NaN,15th,St,...,NaN,NaN,NaN,NaN,8.0,Mission,94103,"(37.766508011617525, -122.42470825254468)",1476234157693,NaN
35,M824007,8,otc alterations permit,2017-08-25,0749,006A,1445,NaN,Eddy,St,...,NaN,NaN,NaN,NaN,5.0,Western Addition,94115,"(37.7813061748427, -122.43142154292566)",147627380882,NaN
36,M824127,8,otc alterations permit,2017-08-28,6551,023,1383,NaN,Church,St,...,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114,"(37.748779856735744, -122.42683572581998)",1476358207225,NaN
37,M824927,8,otc alterations permit,2017-08-29,6597,024,681,NaN,San Jose,Av,...,NaN,NaN,NaN,NaN,8.0,Bernal Heights,94110,"(37.74446179156465, -122.42217241874201)",1476706208668,NaN
38,M825267,8,otc alterations permit,2017-08-29,1572,017,606,NaN,30th,Av,...,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94121,"(37.77767213358907, -122.48966493609916)",1476720105056,NaN
39,M828787,8,otc alterations permit,2017-09-07,0177,022,655,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,3.0,Chinatown,94133,"(37.79673343870443, -122.40610115140781)",1477872407335,0
40,M829567,8,otc alterations permit,2017-09-08,0490,002,3325,NaN,Steiner,St,...,NaN,NaN,NaN,NaN,2.0,Marina,94123,"(37.80002156448977, -122.43806594677513)",147813971761,NaN
41,M832207,8,otc alterations permit,2017-09-15,1609,021F,700,NaN,36th,Av,...,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94121,"(37.77554028396788, -122.49601102992328)",1479528106617,NaN
42,201709158571,8,otc alterations permit,2017-09-15,1429,010,249,NaN,04th,Av,...,5.0,wood frame (5),5.0,wood frame (5),1.0,Inner Richmond,94118,"(37.7839252036892, -122.46267353170244)",1479741242383,NaN
43,M833229,8,otc alterations permit,2017-09-19,0605,028,2379,NaN,Jackson,St,...,NaN,NaN,NaN,NaN,2.0,Pacific Heights,94115,"(37.792266300903314, -122.4340191358936)",1480161420671,1
44,M834107,8,otc alterations permit,2017-09-21,7151,014,247,NaN,Saint Charles,Av,...,NaN,NaN,NaN,NaN,7.0,Oceanview/Merced/Ingleside,94132,"(37.70944796125683, -122.4690186732598)",1480578483312,0
45,M836287,8,otc alterations permit,2017-09-27,0540,002,2843,NaN,Webster,St,...,NaN,NaN,NaN,NaN,2.0,Marina,94123,"(37.79686934709798, -122.43412132328224)",1481221235128,NaN
46,M836847,8,otc alterations permit,2017-09-28,0959,029,2615,NaN,Divisadero,St,...,NaN,NaN,NaN,NaN,2.0,Pacific Heights,94123,"(37.79391508281414, -122.44195481827035)",1481434475430,NaN
47,M839427,8,otc alterations permit,2017-10-04,6780,034,252,NaN,Cotter,St,...,NaN,NaN,NaN,NaN,11.0,Outer Mission,94112,"(37.729885737657085, -122.43669590253097)",1482203213002,NaN
48,201710110928,8,otc alterations permit,2017-10-11,5934,020,938,NaN,Felton,St,...,5.0,wood frame (5),5.0,wood frame (5),9.0,Portola,94134,"(37.72775517946509, -122.41419227409298)",1482932191681,NaN
49,M842668,8,otc alterations permit,2017-10-11,1558,009,535,NaN,15th,Av,...,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94118,"(37.777944902487455, -122.47412411653805)",1482945104295,NaN

In [329]:
# Define target columns for verification / inspection

target_columns = ["Unit", "Existing Units", "Proposed Units", "Plansets"]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Unit ---
<IntegerArray>
[0, 301, 1, 201, 1007, 401, 510, 726, 3412, 14]
Length: 10, dtype: Int64


--- Unique samples for Existing Units ---
<IntegerArray>
[143, 39, 1, 326, 5, 6, 2, 9, 3, 8]
Length: 10, dtype: Int64


--- Unique samples for Proposed Units ---
<IntegerArray>
[39, 1, 326, 5, 6, 2, 9, 3, 8, 74]
Length: 10, dtype: Int64


--- Unique samples for Plansets ---
<IntegerArray>
[2, 0, 6, 4, 3, 20, 9000, 1]
Length: 8, dtype: Int64

In [330]:
# Define target columns for verification / inspection
target_columns = ["Zipcode", "Unit_Clean", "Description"]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Zipcode ---
['94102' '94109' '94107' '94122' '94124' '94117' '94114' '94131' '94115'
 '94108']


--- Unique samples for Unit_Clean ---
<ArrowStringArray>
['0', '301', '1', '201', '1007', '401', '510', '726', '3412', '14']
Length: 10, dtype: str


--- Unique samples for Description ---
<ArrowStringArray>
['ground fl facade: to erect illuminated, electric, wall, single faced sign. n/a for maher ordinance 155-13.',
                                                                    'remove (e) awning and associated signs.',
                                                                            'installation of separating wall',
                                                                   'repair dryrot & stucco at front of bldg.',
                                                         'demolish retail/office/commercial 3-story building',
                                                                                                  'evac maps',
                                                                                                 're-roofing',
                                                                                                'streetspace',
                                                                                        'street space permit',
                                                                                               'street space']
Length: 10, dtype: str

In [331]:
# Define target columns for verification / inspection
target_columns = ["Permit Creation Date", "Current Status Date", "Filed Date", 
    "Issued Date"]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Permit Creation Date ---
<DatetimeArray>
['2015-05-06 00:00:00', '2016-04-19 00:00:00', '2016-05-27 00:00:00',
 '2016-11-07 00:00:00', '2016-11-28 00:00:00', '2017-06-14 00:00:00',
 '2017-06-30 00:00:00', '2017-07-05 00:00:00', '2017-07-06 00:00:00',
 '2017-07-07 00:00:00']
Length: 10, dtype: datetime64[us]


--- Unique samples for Current Status Date ---
<DatetimeArray>
['2017-12-21 00:00:00', '2017-08-03 00:00:00', '2017-09-26 00:00:00',
 '2017-07-24 00:00:00', '2017-12-01 00:00:00', '2017-07-06 00:00:00',
 '2017-07-12 00:00:00', '2017-06-30 00:00:00', '2017-07-05 00:00:00',
 '2017-07-07 00:00:00']
Length: 10, dtype: datetime64[us]


--- Unique samples for Filed Date ---
<DatetimeArray>
['2015-05-06 00:00:00', '2016-04-19 00:00:00', '2016-05-27 00:00:00',
 '2016-11-07 00:00:00', '2016-11-28 00:00:00', '2017-06-14 00:00:00',
 '2017-06-30 00:00:00', '2017-07-05 00:00:00', '2017-07-06 00:00:00',
 '2017-07-07 00:00:00']
Length: 10, dtype: datetime64[us]


--- Unique samples for Issued Date ---
<DatetimeArray>
['2015-11-09 00:00:00', '2017-08-03 00:00:00', '2017-07-18 00:00:00',
 '2017-12-01 00:00:00', '2017-07-06 00:00:00', '2017-06-30 00:00:00',
 '2017-07-05 00:00:00', '2017-07-07 00:00:00', '2017-07-10 00:00:00',
 '2017-07-26 00:00:00']
Length: 10, dtype: datetime64[us]

In [332]:
# Define target columns for verification / inspection
target_columns = ["Completed Date", "First Construction Document Date", "Permit Expiration Date"]

# Loop through columns and print unique samples
for col in target_columns:
    print(f"--- Unique samples for {col} ---")
    print(df[col].dropna().unique()[:10])
    print("\n")

--- Unique samples for Completed Date ---
<DatetimeArray>
['2017-07-24 00:00:00', '2017-07-12 00:00:00', '2017-10-31 00:00:00',
 '2017-09-08 00:00:00', '2017-10-04 00:00:00', '2017-10-13 00:00:00',
 '2017-10-10 00:00:00', '2017-09-28 00:00:00', '2018-01-19 00:00:00',
 '2017-09-22 00:00:00']
Length: 10, dtype: datetime64[us]


--- Unique samples for First Construction Document Date ---
<DatetimeArray>
['2015-11-09 00:00:00', '2017-08-03 00:00:00', '2017-07-18 00:00:00',
 '2017-11-20 00:00:00', '2017-07-06 00:00:00', '2017-06-30 00:00:00',
 '2017-07-05 00:00:00', '2017-07-07 00:00:00', '2017-07-10 00:00:00',
 '2017-07-26 00:00:00']
Length: 10, dtype: datetime64[us]


--- Unique samples for Permit Expiration Date ---
<DatetimeArray>
['2016-11-03 00:00:00', '2017-12-03 00:00:00', '2018-07-13 00:00:00',
 '2018-12-01 00:00:00', '2018-07-01 00:00:00', '2018-06-25 00:00:00',
 '2018-08-08 00:00:00', '2018-02-16 00:00:00', '2018-04-11 00:00:00',
 '2018-05-27 00:00:00']
Length: 10, dtype: datetime64[us]

In [333]:
# Create a copy dedicated for export formatting
df_export = df.copy()

# 1. Fill missing numerical structural fields to enforce strict integer output
int_cols = ["Unit", "Existing Units", "Proposed Units", "Plansets"]
for col in int_cols:
    if col in df_export.columns:
        df_export[col] = df_export[col].fillna(0).astype("int64")

# 2. Enforce strict string casting for mixed alphanumeric columns
if "Permit Number" in df_export.columns:
    df_export["Permit Number"] = df_export["Permit Number"].astype(str)

# 3. Format datetime values to clean date-only strings
date_cols = [
    "Permit Creation Date", "Current Status Date", "Filed Date", 
    "Issued Date", "Completed Date", "First Construction Document Date", 
    "Permit Expiration Date"
]
for col in date_cols:
    if col in df_export.columns:
        df_export[col] = df_export[col].dt.strftime("%Y-%m-%d").fillna("")

# 4. Save to a finalized distribution CSV
df_export.to_csv("san_francisco_building_permits_clean.csv", index=False)

In [ ]:
# Save the clean production data to a new CSV file without the internal index
df.to_csv("clean_SanFrancisco_Building_Permits_data.csv", index=False)
print("Data export successful. Ready for import.")

Data export successful. Ready for import.