In [62]:
print(df_locations.shape)
print(df_locations.columns)
print(df_locations.info())
df_locations.head(50)

(18365, 17)
Index(['address_components', 'formatted_address',
       'geometry.bounds.northeast.lat', 'geometry.bounds.northeast.lng',
       'geometry.bounds.southwest.lat', 'geometry.bounds.southwest.lng',
       'geometry.location.lat', 'geometry.location.lng',
       'geometry.location_type', 'geometry.viewport.northeast.lat',
       'geometry.viewport.northeast.lng', 'geometry.viewport.southwest.lat',
       'geometry.viewport.southwest.lng', 'location_name', 'partial_match',
       'place_id', 'types'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 18365 entries, 0 to 18364
Data columns (total 17 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   address_components               18365 non-null  str
 1   formatted_address                18365 non-null  str
 2   geometry.bounds.northeast.lat    14139 non-null  float64
 3   geometry.bounds.northeast.lng    14139 non-null  float64
 4   geometry.bounds.southwest.lat    14139 non-null  float64
 5   geometry.bounds.southwest.lng    14139 non-null  float64
 6   geometry.location.lat            18365 non-null  float64
 7   geometry.location.lng            18365 non-null  float64
 8   geometry.location_type           18365 non-null  str
 9   geometry.viewport.northeast.lat  18365 non-null  float64
 10  geometry.viewport.northeast.lng  18365 non-null  float64
 11  geometry.viewport.southwest.lat  18365 non-null  float64
 12  geometry.viewport.southwest.lng  18365 non-null  float64
 13  location_name                    18365 non-null  str
 14  partial_match                    4277 non-null   object
 15  place_id                         18363 non-null  str
 16  types                            18365 non-null  str
dtypes: float64(10), object(1), str(6)
memory usage: 11.9+ MB
None

,address_components,formatted_address,geometry.bounds.northeast.lat,geometry.bounds.northeast.lng,geometry.bounds.southwest.lat,geometry.bounds.southwest.lng,geometry.location.lat,geometry.location.lng,geometry.location_type,geometry.viewport.northeast.lat,geometry.viewport.northeast.lng,geometry.viewport.southwest.lat,geometry.viewport.southwest.lng,location_name,partial_match,place_id,types
0,"[{'long_name': 'Managua', 'short_name': 'Manag...","Managua, Nicaragua",12.175357,-86.125088,12.019961,-86.391833,12.114993,-86.236174,APPROXIMATE,12.175357,-86.125088,12.019961,-86.391833,"Managua, Nicaragua",NaN,ChIJC4gH2Q1WcY8RakxPFKL0Xmw,"['locality', 'political']"
1,"[{'long_name': 'Lahore', 'short_name': 'Lahore...","Lahore, Pakistan",31.698486,74.587397,31.267394,74.115539,31.520370,74.358747,APPROXIMATE,31.698486,74.587397,31.267394,74.115539,"Lahore, Pakistan",NaN,ChIJ2QeB5YMEGTkRYiR-zGy-OsI,"['locality', 'political']"
2,"[{'long_name': 'Kaduna', 'short_name': 'Kaduna...","Kaduna, Nigeria",10.616996,7.508812,10.397157,7.349789,10.510464,7.416505,APPROXIMATE,10.616996,7.508812,10.397157,7.349789,"Kaduna, Nigeria",NaN,ChIJdRc3NFg1TRARdOG_mpeVAUg,"['locality', 'political']"
3,"[{'long_name': 'Cusco', 'short_name': 'Cusco',...","Cusco, Peru",-13.497391,-71.853332,-13.562648,-72.025166,-13.531950,-71.967463,APPROXIMATE,-13.497391,-71.853332,-13.562648,-72.025166,"Cusco, Peru",NaN,ChIJMYRZJtjVbZERXTEYI8yWqSo,"['locality', 'political']"
4,"[{'long_name': 'León', 'short_name': 'León', '...","León, Nicaragua",12.460966,-86.843405,12.407026,-86.920753,12.431553,-86.872215,APPROXIMATE,12.460966,-86.843405,12.407026,-86.920753,"Leon, Nicaragua",NaN,ChIJd3qPu5IfcY8RPDHqZG_AtTo,"['locality', 'political']"
5,"[{'long_name': 'Dar es Salaam', 'short_name': ...","Dar es Salaam, Tanzania",-6.588899,39.481711,-6.950283,39.026871,-6.792354,39.208328,APPROXIMATE,-6.588899,39.481711,-6.950283,39.026871,"Dar es Salaam, Tanzania",NaN,ChIJ8dabFq5LXBgR3aGGoCZrD5Q,"['locality', 'political']"
6,"[{'long_name': 'La Paz', 'short_name': 'La Paz...","La Paz, Bolivia",-16.424560,-68.011293,-16.616865,-68.236862,-16.489689,-68.119294,APPROXIMATE,-16.424560,-68.011293,-16.616865,-68.236862,"La Paz, Bolivia",NaN,ChIJD6T1BArfXpERs4pFtHb821c,"['locality', 'political']"
7,"[{'long_name': 'Kampala', 'short_name': 'Kampa...","Kampala, Uganda",0.413199,32.689280,0.212860,32.508971,0.347596,32.582520,APPROXIMATE,0.413199,32.689280,0.212860,32.508971,"Kampala, Uganda",NaN,ChIJm7N0nQ-8fRcR7G9r2T2QOEU,"['locality', 'political']"
8,"[{'long_name': 'Ayacucho', 'short_name': 'Ayac...","Ayacucho, Peru",-13.119257,-74.180044,-13.197473,-74.244564,-13.163874,-74.223564,APPROXIMATE,-13.119257,-74.180044,-13.197473,-74.244564,"Ayacucho, Peru",NaN,ChIJ6b6y9Yh9EpERbqFwOoTLs-k,"['locality', 'political']"
9,"[{'long_name': 'Rawalpindi', 'short_name': 'RW...","Rawalpindi, Pakistan",33.664704,73.153278,33.458325,72.889134,33.565111,73.016914,APPROXIMATE,33.664704,73.153278,33.458325,72.889134,"Rawalpindi, Pakistan",NaN,ChIJy5pBdImU3zgRD9MyFn41hAk,"['locality', 'political']"
10,"[{'long_name': 'Kabankalan', 'short_name': 'Ka...","Kabankalan, Negros Occidental, Philippines",10.063262,122.985849,9.576037,122.717285,9.913412,122.853576,APPROXIMATE,10.063262,122.985849,9.576037,122.717285,"Kabankalan, Negros Occidental, Philippines",NaN,ChIJpW1BAiUTrDMR7qeRyQupslw,"['locality', 'political']"
11,"[{'long_name': 'Kitale', 'short_name': 'Kitale...","Kitale, Kenya",1.063417,35.041710,0.968692,34.967872,1.019089,35.002305,APPROXIMATE,1.063417,35.041710,0.968692,34.967872,"Kitale, Kenya",NaN,ChIJxZPE-P8mghcRXPMRqBD5U0A,"['locality', 'political']"
12,"[{'long_name': 'Eldoret', 'short_name': 'Eldor...","Eldoret, Kenya",0.578829,35.314682,0.444684,35.223742,0.514277,35.269780,APPROXIMATE,0.578829,35.314682,0.444684,35.223742,"Eldoret, Kenya",NaN,ChIJNfX5N64BgRcRIAj88H0z2-I,"['locality', 'political']"
13,"[{'long_name': 'Narra', 'short_name': 'Narra',...","Narra, Palawan, Philippines",9.460746,118.518619,9.099724,118.066978,9.250630,118.346195,APPROXIMATE,9.460746,118.518619,9.099724,118.066978,"Narra, Palawan, Philippines",NaN,ChIJD4XG4hs2NTIRHEx_KKExwv0,"['locality', 'political']"
14,"[{'long_name': 'Pucallpa', 'short_name': 'Puca...","Pucallpa, Peru",-8.316900,-74.518461,-8.433319,-74.644976,-8.392862,-74.582617,APPROXIMATE,-8.316900,-74.518461,-8.433319,-74.644976,"PUCALLPA, Peru",NaN,ChIJYUTr8vO8o5ERQ9-UtZhiAEk,"['locality', 'political']"
15,"[{'long_name': 'Likoni', 'short_name': 'Likoni...","Likoni, Mombasa, Kenya",-4.079346,39.674774,-4.099795,39.647079,-4.092902,39.661445,APPROXIMATE,-4.079346,39.674774,-4.099795,39.647079,"Likoni, Kenya",NaN,ChIJLXFdP1cTQBgRbjQzj9uzYYA,"['political', 'sublocality', 'sublocality_leve..."
16,"[{'long_name': ""Brooke's Point"", 'short_name':...","Brooke's Point, Palawan, Philippines",8.998009,118.019943,8.668936,117.679367,8.818934,117.784246,APPROXIMATE,8.998009,118.019943,8.668936,117.679367,"Brookes Point, Palawan, Philippines",NaN,ChIJZecGp8D-NDIRAWTMMKuoFgY,"['locality', 'political']"
17,"[{'long_name': 'Portoviejo', 'short_name': 'Po...","Portoviejo, Ecuador",-0.960572,-79.933777,-1.136324,-80.580254,-1.054723,-80.452490,APPROXIMATE,-0.960572,-79.933777,-1.136324,-80.580254,"Portoviejo, Ecuador",NaN,ChIJpWeRNLPyK5AR7n7rE-WA67U,"['locality', 'political']"
18,"[{'long_name': 'Thanh Hóa', 'short_name': 'Tha...","Thanh Hóa, Thanh Hoa, Vietnam",19.884508,105.862949,19.732916,105.719161,19.806692,105.785182,APPROXIMATE,19.884508,105.862949,19.732916,105.719161,"Thanh Hoá, Vietnam",NaN,ChIJdyJ-I_73NjEROiH8ezYyOKE,"['locality', 'political']"
19,"[{'long_name': 'Bais City', 'short_name': 'Bai...","Bais City, Negros Oriental, Philippines",9.682407,123.166351,9.535664,122.891135,9.591569,123.121179,APPROXIMATE,9.682407,123.166351,9.535664,122.891135,"Bais, Negros Oriental, Philippines",NaN,ChIJyTVBTCt5rDMRouQAUsvj6CU,"['locality', 'political']"
20,"[{'long_name': 'Cordova', 'short_name': 'Cordo...","Cordova, Cebu, Philippines",10.279862,124.009982,10.184658,123.893656,10.243864,123.941552,APPROXIMATE,10.279862,124.009982,10.184658,123.893656,"Cordova, Cebu, Philippines",NaN,ChIJi0WpTF-aqTMRnQrxQZG5VAs,"['locality', 'political']"
21,"[{'long_name': 'Medellin', 'short_name': 'Mede...","Medellin, Antioquia, Colombia",6.373637,-75.473410,6.163719,-75.719374,6.244203,-75.581212,APPROXIMATE,6.373637,-75.473410,6.163719,-75.719374,"Medellín, Colombia",NaN,ChIJ291STu8oRI4RcqxwksPWL3I,"['administrative_area_level_2', 'political']"
22,"[{'long_name': 'Barranquilla', 'short_name': '...","Barranquilla, Atlantico, Colombia",11.046332,-74.758539,10.921292,-74.877496,11.004107,-74.806981,APPROXIMATE,11.046332,-74.758539,10.921292,-74.877496,"Barranquilla, Colombia",NaN,ChIJBeYq0UQt9I4Rshe5gUWEMyY,"['locality', 'political']"
23,"[{'long_name': 'Nakuru', 'short_name': 'Nakuru...","Nakuru, Kenya",-0.208311,36.197237,-0.423313,35.960484,-0.303099,36.080026,APPROXIMATE,-0.208311,36.197237,-0.423313,35.960484,"Nakuru, Kenya",NaN,ChIJ7wthz5CNKRgRGsJ8vDMY8vI,"['locality', 'political']"
24,"[{'long_name': 'Quezon', 'short_name': 'Quezon...","Quezon, Palawan, Philippines",9.553609,118.335114,8.998348,117.718162,9.418463,118.252662,APPROXIMATE,9.553609,118.335114,8.998348,117.718162,"Quezon, Palawan, Philippines",NaN,ChIJi4uruikvNTIRpJnR_HZgatQ,"['locality', 'political']"
25,"[{'long_name': 'Palo', 'short_name': 'Palo', '...","Palo, Leyte, Philippines",11.192211,125.021668,11.095704,124.911632,11.158383,124.991888,APPROXIMATE,11.192211,125.021668,11.095704,124.911632,"Palo, Leyte, Philippines",NaN,ChIJK0FOiWbYBzMRM0PS7unDgsA,"['locality', 'political']"
26,"[{'long_name': 'Masaya', 'short_name': 'Masaya...","Masaya, Nicaragua",11.997598,-86.072121,11.952426,-86.113329,11.970448,-86.088637,APPROXIMATE,11.997598,-86.072121,11.952426,-86.113329,"Masaya, Nicaragua",NaN,ChIJKRUckR0GdI8R0moxUGHN1vI,"['locality', 'political']"
27,"[{'long_name': 'Kisauni', 'short_name': 'Kisau...","Kisauni, Mombasa, Kenya",-4.011375,39.711655,-4.038996,39.673308,-4.022620,39.687933,APPROXIMATE,-4.011375,39.711655,-4.038996,39.673308,"Kisauni, Kenya",NaN,ChIJjb0Tkn8NQBgRuvIU_xl3SNc,"['political', 'sublocality', 'sublocality_leve..."
28,"[{'long_name': 'Kasese', 'short_name': 'Kasese...","Kasese, Uganda",0.193290,30.107088,0.150289,30.061589,0.169899,30.078078,APPROXIMATE,0.193290,30.107088,0.150289,30.061589,"Kasese, Uganda",NaN,ChIJ27nqCi3yYRcRcP7Ml11wWSQ,"['locality', 'political']"
29,"[{'long_name': 'Khujand', 'short_name': 'Khuja...","Khujand, Tajikistan",40.335161,69.727993,40.233674,69.545860,40.267515,69.645288,APPROXIMATE,40.335161,69.727993,40.233674,69.545860,"Khujand, Tajikistan",NaN,ChIJDT6rw92ysTgRN-5Pz0XcTB8,"['locality', 'political']"
30,"[{'long_name': 'San Miguel', 'short_name': 'Sa...","San Miguel, El Salvador",13.526815,-88.112068,13.430220,-88.226110,13.479292,-88.177918,APPROXIMATE,13.526815,-88.112068,13.430220,-88.226110,"San Miguel, El Salvador",NaN,ChIJqw2DvHAqe48RklXsbkCcrHY,"['locality', 'political']"
31,"[{'long_name': 'Kisumu', 'short_name': 'Kisumu...","Kisumu, Kenya",0.037508,34.901247,-0.187454,34.575090,-0.091702,34.767957,APPROXIMATE,0.037508,34.901247,-0.187454,34.575090,"Kisumu, Kenya",NaN,ChIJHchKrTekKhgR0o0k1jmkEiA,"['locality', 'political']"
32,"[{'long_name': 'Phnom Penh', 'short_name': 'PP...","Phnom Penh, Cambodia",11.736327,105.067577,11.422401,104.712796,11.544873,104.892167,APPROXIMATE,11.736327,105.067577,11.422401,104.712796,"Phnom Penh, Cambodia",NaN,ChIJ42tqxz1RCTERuyW1WugOAZw,"['locality', 'political']"
33,"[{'long_name': 'Fort Portal', 'short_name': 'F...","Fort Portal, Uganda",0.679944,30.296460,0.625499,30.253374,0.654626,30.280117,APPROXIMATE,0.679944,30.296460,0.625499,30.253374,"Fort Portal, Uganda",NaN,ChIJwUHNPELaYxcRUEdocKxcEbM,"['locality', 'political']"
34,"[{'long_name': 'Boane District', 'short_name':...","Boane District, Mozambique",-25.769004,32.498644,-26.287666,32.183632,-26.112894,32.310752,APPROXIMATE,-25.769004,32.498644,-26.287666,32.183632,"Boane, Maputo, Mozambique",NaN,ChIJAf1L4p195h4RuuDVZG6L8rQ,"['administrative_area_level_2', 'political']"
35,"[{'long_name': 'Dumaguete', 'short_name': 'Dum...","Dumaguete, Negros Oriental, Philippines",9.332478,123.313798,9.258986,123.250337,9.306840,123.305447,APPROXIMATE,9.332478,123.313798,9.258986,123.250337,"Dumaguete, Negros Oriental, Philippines",NaN,ChIJ96COeNtuqzMR-zf8W5v-ndc,"['locality', 'political']"
36,"[{'long_name': 'Tarma', 'short_name': 'Tarma',...","Tarma, Peru",-11.391523,-75.660267,-11.481202,-75.714941,-11.419335,-75.688949,APPROXIMATE,-11.391523,-75.660267,-11.481202,-75.714941,"TARMA, Peru",NaN,ChIJGXWgCpQgCZERwVdx0EBd98c,"['locality', 'political']"
37,"[{'long_name': 'Cusco', 'short_name': 'Cusco',...","Cusco, Peru",-13.497391,-71.853332,-13.562648,-72.025166,-13.531950,-71.967463,APPROXIMATE,-13.497391,-71.853332,-13.562648,-72.025166,"CUSCO, Peru",NaN,ChIJMYRZJtjVbZERXTEYI8yWqSo,"['locality', 'political']"
38,"[{'long_name': 'Multan', 'short_name': 'Multan...","Multan, Pakistan",30.310533,71.645387,30.051979,71.303930,30.157458,71.524915,APPROXIMATE,30.310533,71.645387,30.051979,71.303930,"Multan, Pakistan",NaN,ChIJ2afeeFcxOzkRL9RVTscv17o,"['locality', 'political']"
39,"[{'long_name': 'Talibon', 'short_name': 'Talib...","Talibon, Bohol, Philippines",10.257155,124.368153,10.027008,124.214162,10.157695,124.264387,APPROXIMATE,10.257155,124.368153,10.027008,124.214162,"Talibon, Bohol, Philippines",NaN,ChIJn0ymbLrxqTMRm7E7XdDMEWo,"['locality', 'political']"
40,"[{'long_name': 'El Alto', 'short_name': 'El Al...","El Alto, Bolivia",-16.444216,-68.129482,-16.649586,-68.298908,-16.500094,-68.214686,APPROXIMATE,-16.444216,-68.129482,-16.649586,-68.298908,"El Alto, Bolivia",NaN,ChIJcyQuhL7eXpERj534Fy-KHzo,"['locality', 'political']"
41,"[{'long_name': 'Msambweni', 'short_name': 'Msa...","Msambweni, Kenya",-4.454453,39.496880,-4.487012,39.461088,-4.465290,39.481266,APPROXIMATE,-4.454453,39.496880,-4.487012,39.461088,"Msambweni, Kenya",NaN,ChIJ4xGXL4-tQRgRkyWdGvj4hR0,"['locality', 'political']"
42,"[{'long_name': 'Benin City', 'short_name': 'Be...","Benin City, Nigeria",6.459025,5.738640,6.236125,5.546293,6.334986,5.603746,APPROXIMATE,6.459025,5.738640,6.236125,5.546293,"Benin City, Nigeria",NaN,ChIJ8azPeWLTQBARoN9YV8AQqoQ,"['locality', 'political']"
43,"[{'long_name': 'Limuru Road', 'short_name': 'L...","Limuru Rd, Nairobi, Kenya",NaN,NaN,NaN,NaN,-1.226668,36.805231,GEOMETRIC_CENTER,-1.225319,36.806580,-1.228017,36.803882,"Tiribe, Kenya",True,ChIJh4YVjQIXLxgRN3DTrYqBnAI,"['establishment', 'lodging', 'point_of_interest']"
44,"[{'long_name': 'Turtle Bay Road', 'short_name'...","Tribe Watersports (opposite) Plot 28,, Turtle ...",NaN,NaN,NaN,NaN,-3.375725,39.986635,GEOMETRIC_CENTER,-3.374376,39.987984,-3.377074,39.985286,"Tiribe, Kenya",True,ChIJR1dhtzyAFRgR0bWNt19WBio,"['establishment', 'point_of_interest', 'store']"
45,"[{'long_name': 'Usulutan', 'short_name': 'Usul...","Usulutan, El Salvador",13.353713,-88.427668,13.332834,-88.457880,13.345311,-88.442811,APPROXIMATE,13.353713,-88.427668,13.332834,-88.457880,"Usulután, El Salvador",NaN,ChIJ73D0kdA5e48RIB_J7tgEUNg,"['locality', 'political']"
46,"[{'long_name': 'San Gabriel', 'short_name': 'S...","San Gabriel, Ecuador",0.606511,-77.819059,0.585655,-77.839572,0.594895,-77.828151,APPROXIMATE,0.606511,-77.819059,0.585655,-77.839572,"San Gabriel, Ecuador",NaN,ChIJE7e6T7R4KY4R1M7d03xP53A,"['locality', 'political']"
47,"[{'long_name': 'Hinigaran', 'short_name': 'Hin...","Hinigaran, Negros Occidental, Philippines",10.277086,122.859249,10.264840,122.848692,10.271355,122.854985,APPROXIMATE,10.277086,122.859249,10.264840,122.848692,"Hinigaran, Negros Occidental, Philippines",NaN,ChIJ3dtxztKlrjMRJu09d6MQS8Q,"['locality', 'political']"
48,"[{'long_name': 'Lima', 'short_name': 'Lima', '...","Lima, Peru",-11.799988,-76.788340,-12.253289,-77.187219,-12.046373,-77.042754,APPROXIMATE,-11.799988,-76.788340,-12.253289,-77.187219,"Lima, Peru",NaN,ChIJxz7uGfbFBZERSi5FzLlsIBQ,"['colloquial_area', 'locality', 'political']"
49,"[{'long_name': 'Ho Chi Minh City', 'short_name...","Ho Chi Minh City, Vietnam",11.160214,107.026577,10.349370,106.363878,10.823099,106.629664,APPROXIMATE,11.160214,107.026577,10.349370,106.363878,"Ho Chi Minh City, Vietnam",NaN,ChIJ0T2NLikpdTERKxE8d61aX_E,"['locality', 'political']"

In [63]:
# Initialize our clean structural copy from your exact step
df_locations_clean = df_locations.copy()

# Standardize column names to lowercase
df_locations_clean.columns = df_locations_clean.columns.str.strip().str.lower()

# Define numerical coordinate columns that must preserve float64 types
coord_cols = [
    "geometry.bounds.northeast.lat", "geometry.bounds.northeast.lng",
    "geometry.bounds.southwest.lat", "geometry.bounds.southwest.lng",
    "geometry.location.lat", "geometry.location.lng",
    "geometry.viewport.northeast.lat", "geometry.viewport.northeast.lng",
    "geometry.viewport.southwest.lat", "geometry.viewport.southwest.lng"
]

# Define categorical and text columns
text_cols = [
    "address_components", "formatted_address", "geometry.location_type",
    "location_name", "partial_match", "place_id", "types"
]

# Process text columns safely without altering float columns
for col in text_cols:
    if col in df_locations_clean.columns:
        df_locations_clean[col] = df_locations_clean[col].astype(str).str.strip()
        df_locations_clean[col] = df_locations_clean[col].replace(["nan", "NaN", "", "None"], "Unknown")
        df_locations_clean[col] = df_locations_clean[col].fillna("Unknown")

# Gather all structural metrics
missing_count = df_locations_clean.isnull().sum()
missing_percent = (df_locations_clean.isnull().sum() / len(df_locations_clean)) * 100
column_types = df_locations_clean.dtypes

# Combine them into a single DataFrame
full_report_locations = pd.DataFrame({
    "Data Type": column_types,
    "Missing Count": missing_count,
    "Missing %": missing_percent
})

# Note: We do not sort by "Missing %" here so that the columns and rows stay in their original order (0 to 102), making slicing accurate.

# Columns 1 to 25
print(f"Total Rows, {df_locations_clean.shape[0]}")
print(f"Total Columns, {df_locations_clean.shape[1]}")
print(f"Exact Duplicate Rows, {df_locations_clean.duplicated().sum()}")

print(full_report_locations.iloc[0:25])

# Strip hidden spaces from categorical string columns
locations_cols = ['address_components', 
    'formatted_address',
    'geometry.bounds.northeast.lat',
    'geometry.bounds.northeast.lng',
    'geometry.bounds.southwest.lat',
    'geometry.bounds.southwest.lng',
    'geometry.location.lat',
    'geometry.location.lng',
    'geometry.location_type',
    'geometry.viewport.northeast.lat',
    'geometry.viewport.northeast.lng',
    'geometry.viewport.southwest.lat',
    'geometry.viewport.southwest.lng',
    'location_name',
    'partial_match',
    'place_id',
    'types'
    ]

Total Rows, 18365
Total Columns, 17
Exact Duplicate Rows, 3
                                Data Type  Missing Count  Missing %
address_components                    str              0   0.000000
formatted_address                     str              0   0.000000
geometry.bounds.northeast.lat     float64           4226  23.011163
geometry.bounds.northeast.lng     float64           4226  23.011163
geometry.bounds.southwest.lat     float64           4226  23.011163
geometry.bounds.southwest.lng     float64           4226  23.011163
geometry.location.lat             float64              0   0.000000
geometry.location.lng             float64              0   0.000000
geometry.location_type                str              0   0.000000
geometry.viewport.northeast.lat   float64              0   0.000000
geometry.viewport.northeast.lng   float64              0   0.000000
geometry.viewport.southwest.lat   float64              0   0.000000
geometry.viewport.southwest.lng   float64              0   0.000000
location_name                         str              0   0.000000
partial_match                         str              0   0.000000
place_id                              str              0   0.000000
types                                 str              0   0.000000

In [64]:
# Define the full set of geographic categories present in the data
countries = []
state_provinces = []
district_counties = []
city_towns = []
neighborhoods = []
local_areas = []
streets = []
postal_codes = []

# Parse the address components row by row
for record in df_locations_clean["address_components"]:
    country = "Unknown"
    state_province = "Unknown"
    district_county = "Unknown"
    city_town = "Unknown"
    neighborhood = "Unknown"
    local_area = "Unknown"
    street = "Unknown"
    postal_code = "Unknown"
    
    try:
        components = eval(record)
        if isinstance(components, list):
            for item in components:
                types = item.get("types", [])
                long_name = item.get("long_name", "Unknown")
                
                if "country" in types:
                    country = long_name
                elif "administrative_area_level_1" in types:
                    state_province = long_name
                elif "administrative_area_level_2" in types:
                    district_county = long_name
                elif "locality" in types:
                    city_town = long_name
                elif "sublocality_level_1" in types or "sublocality" in types:
                    neighborhood = long_name
                elif "neighborhood" in types:
                    local_area = long_name
                elif "route" in types:
                    street = long_name
                elif "postal_code" in types:
                    postal_code = long_name
    except Exception:
        pass
        
    countries.append(country)
    state_provinces.append(state_province)
    district_counties.append(district_county)
    city_towns.append(city_town)
    neighborhoods.append(neighborhood)
    local_areas.append(local_area)
    streets.append(street)
    postal_codes.append(postal_code)

# Map all structural fields back to the DataFrame
df_locations_clean["country"] = countries
df_locations_clean["state_province"] = state_provinces
df_locations_clean["district_county"] = district_counties
df_locations_clean["city_town"] = city_towns
df_locations_clean["neighborhood_suburb"] = neighborhoods
df_locations_clean["local_area"] = local_areas
df_locations_clean["street_name"] = streets
df_locations_clean["postal_code"] = postal_codes

# Drop the raw address column and handle exact duplicate rows
df_locations_clean = df_locations_clean.drop(columns=["address_components"])
df_locations_clean = df_locations_clean.drop_duplicates()

# Verify the complete breakdown
print("--- Complete Extracted Field Verification ---")
print(f"Total Rows, {df_locations_clean.shape[0]}")
print(f"Total Columns, {df_locations_clean.shape[1]}")
print(f"Exact Duplicate Rows, {df_locations_clean.duplicated().sum()}")

--- Complete Extracted Field Verification ---
Total Rows, 18362
Total Columns, 24
Exact Duplicate Rows, 0

In [65]:
df_locations_clean.head(50)

,formatted_address,geometry.bounds.northeast.lat,geometry.bounds.northeast.lng,geometry.bounds.southwest.lat,geometry.bounds.southwest.lng,geometry.location.lat,geometry.location.lng,geometry.location_type,geometry.viewport.northeast.lat,geometry.viewport.northeast.lng,...,place_id,types,country,state_province,district_county,city_town,neighborhood_suburb,local_area,street_name,postal_code
0,"Managua, Nicaragua",12.175357,-86.125088,12.019961,-86.391833,12.114993,-86.236174,APPROXIMATE,12.175357,-86.125088,...,ChIJC4gH2Q1WcY8RakxPFKL0Xmw,"['locality', 'political']",Nicaragua,Managua Department,Unknown,Managua,Unknown,Unknown,Unknown,Unknown
1,"Lahore, Pakistan",31.698486,74.587397,31.267394,74.115539,31.520370,74.358747,APPROXIMATE,31.698486,74.587397,...,ChIJ2QeB5YMEGTkRYiR-zGy-OsI,"['locality', 'political']",Pakistan,Punjab,Lahore,Lahore,Unknown,Unknown,Unknown,Unknown
2,"Kaduna, Nigeria",10.616996,7.508812,10.397157,7.349789,10.510464,7.416505,APPROXIMATE,10.616996,7.508812,...,ChIJdRc3NFg1TRARdOG_mpeVAUg,"['locality', 'political']",Nigeria,Kaduna,Unknown,Kaduna,Unknown,Unknown,Unknown,Unknown
3,"Cusco, Peru",-13.497391,-71.853332,-13.562648,-72.025166,-13.531950,-71.967463,APPROXIMATE,-13.497391,-71.853332,...,ChIJMYRZJtjVbZERXTEYI8yWqSo,"['locality', 'political']",Peru,Cusco,Cusco,Cusco,Unknown,Unknown,Unknown,Unknown
4,"León, Nicaragua",12.460966,-86.843405,12.407026,-86.920753,12.431553,-86.872215,APPROXIMATE,12.460966,-86.843405,...,ChIJd3qPu5IfcY8RPDHqZG_AtTo,"['locality', 'political']",Nicaragua,León Department,Unknown,León,Unknown,Unknown,Unknown,Unknown
5,"Dar es Salaam, Tanzania",-6.588899,39.481711,-6.950283,39.026871,-6.792354,39.208328,APPROXIMATE,-6.588899,39.481711,...,ChIJ8dabFq5LXBgR3aGGoCZrD5Q,"['locality', 'political']",Tanzania,Dar es Salaam,Kinondoni,Dar es Salaam,Unknown,Unknown,Unknown,Unknown
6,"La Paz, Bolivia",-16.424560,-68.011293,-16.616865,-68.236862,-16.489689,-68.119294,APPROXIMATE,-16.424560,-68.011293,...,ChIJD6T1BArfXpERs4pFtHb821c,"['locality', 'political']",Bolivia,La Paz Department,Unknown,La Paz,Unknown,Unknown,Unknown,Unknown
7,"Kampala, Uganda",0.413199,32.689280,0.212860,32.508971,0.347596,32.582520,APPROXIMATE,0.413199,32.689280,...,ChIJm7N0nQ-8fRcR7G9r2T2QOEU,"['locality', 'political']",Uganda,Central Region,Kampala,Kampala,Unknown,Unknown,Unknown,Unknown
8,"Ayacucho, Peru",-13.119257,-74.180044,-13.197473,-74.244564,-13.163874,-74.223564,APPROXIMATE,-13.119257,-74.180044,...,ChIJ6b6y9Yh9EpERbqFwOoTLs-k,"['locality', 'political']",Peru,Ayacucho,Huamanga,Ayacucho,Unknown,Unknown,Unknown,Unknown
9,"Rawalpindi, Pakistan",33.664704,73.153278,33.458325,72.889134,33.565111,73.016914,APPROXIMATE,33.664704,73.153278,...,ChIJy5pBdImU3zgRD9MyFn41hAk,"['locality', 'political']",Pakistan,Punjab,Rawalpindi,Rawalpindi,Unknown,Unknown,Unknown,Unknown
10,"Kabankalan, Negros Occidental, Philippines",10.063262,122.985849,9.576037,122.717285,9.913412,122.853576,APPROXIMATE,10.063262,122.985849,...,ChIJpW1BAiUTrDMR7qeRyQupslw,"['locality', 'political']",Philippines,Western Visayas,Negros Occidental,Kabankalan,Unknown,Unknown,Unknown,Unknown
11,"Kitale, Kenya",1.063417,35.041710,0.968692,34.967872,1.019089,35.002305,APPROXIMATE,1.063417,35.041710,...,ChIJxZPE-P8mghcRXPMRqBD5U0A,"['locality', 'political']",Kenya,Trans-Nzoia County,Unknown,Kitale,Unknown,Unknown,Unknown,Unknown
12,"Eldoret, Kenya",0.578829,35.314682,0.444684,35.223742,0.514277,35.269780,APPROXIMATE,0.578829,35.314682,...,ChIJNfX5N64BgRcRIAj88H0z2-I,"['locality', 'political']",Kenya,Uasin Gishu County,Unknown,Eldoret,Unknown,Unknown,Unknown,Unknown
13,"Narra, Palawan, Philippines",9.460746,118.518619,9.099724,118.066978,9.250630,118.346195,APPROXIMATE,9.460746,118.518619,...,ChIJD4XG4hs2NTIRHEx_KKExwv0,"['locality', 'political']",Philippines,MIMAROPA,Palawan,Narra,Unknown,Unknown,Unknown,Unknown
14,"Pucallpa, Peru",-8.316900,-74.518461,-8.433319,-74.644976,-8.392862,-74.582617,APPROXIMATE,-8.316900,-74.518461,...,ChIJYUTr8vO8o5ERQ9-UtZhiAEk,"['locality', 'political']",Peru,Ucayali,Coronel Portillo,Pucallpa,Unknown,Unknown,Unknown,Unknown
15,"Likoni, Mombasa, Kenya",-4.079346,39.674774,-4.099795,39.647079,-4.092902,39.661445,APPROXIMATE,-4.079346,39.674774,...,ChIJLXFdP1cTQBgRbjQzj9uzYYA,"['political', 'sublocality', 'sublocality_leve...",Kenya,Coast,Unknown,Mombasa,Likoni,Unknown,Unknown,Unknown
16,"Brooke's Point, Palawan, Philippines",8.998009,118.019943,8.668936,117.679367,8.818934,117.784246,APPROXIMATE,8.998009,118.019943,...,ChIJZecGp8D-NDIRAWTMMKuoFgY,"['locality', 'political']",Philippines,MIMAROPA,Palawan,Brooke's Point,Unknown,Unknown,Unknown,Unknown
17,"Portoviejo, Ecuador",-0.960572,-79.933777,-1.136324,-80.580254,-1.054723,-80.452490,APPROXIMATE,-0.960572,-79.933777,...,ChIJpWeRNLPyK5AR7n7rE-WA67U,"['locality', 'political']",Ecuador,Manabí Province,Unknown,Portoviejo,Unknown,Unknown,Unknown,Unknown
18,"Thanh Hóa, Thanh Hoa, Vietnam",19.884508,105.862949,19.732916,105.719161,19.806692,105.785182,APPROXIMATE,19.884508,105.862949,...,ChIJdyJ-I_73NjEROiH8ezYyOKE,"['locality', 'political']",Vietnam,Thanh Hoa,Unknown,Thanh Hóa,Unknown,Unknown,Unknown,Unknown
19,"Bais City, Negros Oriental, Philippines",9.682407,123.166351,9.535664,122.891135,9.591569,123.121179,APPROXIMATE,9.682407,123.166351,...,ChIJyTVBTCt5rDMRouQAUsvj6CU,"['locality', 'political']",Philippines,Central Visayas,Negros Oriental,Bais City,Unknown,Unknown,Unknown,Unknown
20,"Cordova, Cebu, Philippines",10.279862,124.009982,10.184658,123.893656,10.243864,123.941552,APPROXIMATE,10.279862,124.009982,...,ChIJi0WpTF-aqTMRnQrxQZG5VAs,"['locality', 'political']",Philippines,Central Visayas,Cebu,Cordova,Unknown,Unknown,Unknown,Unknown
21,"Medellin, Antioquia, Colombia",6.373637,-75.473410,6.163719,-75.719374,6.244203,-75.581212,APPROXIMATE,6.373637,-75.473410,...,ChIJ291STu8oRI4RcqxwksPWL3I,"['administrative_area_level_2', 'political']",Colombia,Antioquia,Medellin,Unknown,Unknown,Unknown,Unknown,Unknown
22,"Barranquilla, Atlantico, Colombia",11.046332,-74.758539,10.921292,-74.877496,11.004107,-74.806981,APPROXIMATE,11.046332,-74.758539,...,ChIJBeYq0UQt9I4Rshe5gUWEMyY,"['locality', 'political']",Colombia,Atlantico,Barranquilla,Barranquilla,Unknown,Unknown,Unknown,Unknown
23,"Nakuru, Kenya",-0.208311,36.197237,-0.423313,35.960484,-0.303099,36.080026,APPROXIMATE,-0.208311,36.197237,...,ChIJ7wthz5CNKRgRGsJ8vDMY8vI,"['locality', 'political']",Kenya,Nakuru County,Unknown,Nakuru,Unknown,Unknown,Unknown,Unknown
24,"Quezon, Palawan, Philippines",9.553609,118.335114,8.998348,117.718162,9.418463,118.252662,APPROXIMATE,9.553609,118.335114,...,ChIJi4uruikvNTIRpJnR_HZgatQ,"['locality', 'political']",Philippines,MIMAROPA,Palawan,Quezon,Unknown,Unknown,Unknown,Unknown
25,"Palo, Leyte, Philippines",11.192211,125.021668,11.095704,124.911632,11.158383,124.991888,APPROXIMATE,11.192211,125.021668,...,ChIJK0FOiWbYBzMRM0PS7unDgsA,"['locality', 'political']",Philippines,Eastern Visayas,Leyte,Palo,Unknown,Unknown,Unknown,Unknown
26,"Masaya, Nicaragua",11.997598,-86.072121,11.952426,-86.113329,11.970448,-86.088637,APPROXIMATE,11.997598,-86.072121,...,ChIJKRUckR0GdI8R0moxUGHN1vI,"['locality', 'political']",Nicaragua,Masaya Department,Unknown,Masaya,Unknown,Unknown,Unknown,Unknown
27,"Kisauni, Mombasa, Kenya",-4.011375,39.711655,-4.038996,39.673308,-4.022620,39.687933,APPROXIMATE,-4.011375,39.711655,...,ChIJjb0Tkn8NQBgRuvIU_xl3SNc,"['political', 'sublocality', 'sublocality_leve...",Kenya,Coast,Unknown,Mombasa,Kisauni,Unknown,Unknown,Unknown
28,"Kasese, Uganda",0.193290,30.107088,0.150289,30.061589,0.169899,30.078078,APPROXIMATE,0.193290,30.107088,...,ChIJ27nqCi3yYRcRcP7Ml11wWSQ,"['locality', 'political']",Uganda,Western Region,Kasese,Kasese,Unknown,Unknown,Unknown,Unknown
29,"Khujand, Tajikistan",40.335161,69.727993,40.233674,69.545860,40.267515,69.645288,APPROXIMATE,40.335161,69.727993,...,ChIJDT6rw92ysTgRN-5Pz0XcTB8,"['locality', 'political']",Tajikistan,Sughd Province,Unknown,Khujand,Unknown,Unknown,Unknown,Unknown
30,"San Miguel, El Salvador",13.526815,-88.112068,13.430220,-88.226110,13.479292,-88.177918,APPROXIMATE,13.526815,-88.112068,...,ChIJqw2DvHAqe48RklXsbkCcrHY,"['locality', 'political']",El Salvador,San Miguel Department,Unknown,San Miguel,Unknown,Unknown,Unknown,Unknown
31,"Kisumu, Kenya",0.037508,34.901247,-0.187454,34.575090,-0.091702,34.767957,APPROXIMATE,0.037508,34.901247,...,ChIJHchKrTekKhgR0o0k1jmkEiA,"['locality', 'political']",Kenya,Kisumu County,Unknown,Kisumu,Unknown,Unknown,Unknown,Unknown
32,"Phnom Penh, Cambodia",11.736327,105.067577,11.422401,104.712796,11.544873,104.892167,APPROXIMATE,11.736327,105.067577,...,ChIJ42tqxz1RCTERuyW1WugOAZw,"['locality', 'political']",Cambodia,Phnom Penh,Unknown,Phnom Penh,Unknown,Unknown,Unknown,Unknown
33,"Fort Portal, Uganda",0.679944,30.296460,0.625499,30.253374,0.654626,30.280117,APPROXIMATE,0.679944,30.296460,...,ChIJwUHNPELaYxcRUEdocKxcEbM,"['locality', 'political']",Uganda,Western Region,Kabarole,Fort Portal,Unknown,Unknown,Unknown,Unknown
34,"Boane District, Mozambique",-25.769004,32.498644,-26.287666,32.183632,-26.112894,32.310752,APPROXIMATE,-25.769004,32.498644,...,ChIJAf1L4p195h4RuuDVZG6L8rQ,"['administrative_area_level_2', 'political']",Mozambique,Maputo Province,Boane District,Unknown,Unknown,Unknown,Unknown,Unknown
35,"Dumaguete, Negros Oriental, Philippines",9.332478,123.313798,9.258986,123.250337,9.306840,123.305447,APPROXIMATE,9.332478,123.313798,...,ChIJ96COeNtuqzMR-zf8W5v-ndc,"['locality', 'political']",Philippines,Central Visayas,Negros Oriental,Dumaguete,Unknown,Unknown,Unknown,Unknown
36,"Tarma, Peru",-11.391523,-75.660267,-11.481202,-75.714941,-11.419335,-75.688949,APPROXIMATE,-11.391523,-75.660267,...,ChIJGXWgCpQgCZERwVdx0EBd98c,"['locality', 'political']",Peru,Junin,Tarma Province,Tarma,Unknown,Unknown,Unknown,Unknown
37,"Cusco, Peru",-13.497391,-71.853332,-13.562648,-72.025166,-13.531950,-71.967463,APPROXIMATE,-13.497391,-71.853332,...,ChIJMYRZJtjVbZERXTEYI8yWqSo,"['locality', 'political']",Peru,Cusco,Cusco,Cusco,Unknown,Unknown,Unknown,Unknown
38,"Multan, Pakistan",30.310533,71.645387,30.051979,71.303930,30.157458,71.524915,APPROXIMATE,30.310533,71.645387,...,ChIJ2afeeFcxOzkRL9RVTscv17o,"['locality', 'political']",Pakistan,Punjab,Multan,Multan,Unknown,Unknown,Unknown,Unknown
39,"Talibon, Bohol, Philippines",10.257155,124.368153,10.027008,124.214162,10.157695,124.264387,APPROXIMATE,10.257155,124.368153,...,ChIJn0ymbLrxqTMRm7E7XdDMEWo,"['locality', 'political']",Philippines,Central Visayas,Bohol,Talibon,Unknown,Unknown,Unknown,Unknown
40,"El Alto, Bolivia",-16.444216,-68.129482,-16.649586,-68.298908,-16.500094,-68.214686,APPROXIMATE,-16.444216,-68.129482,...,ChIJcyQuhL7eXpERj534Fy-KHzo,"['locality', 'political']",Bolivia,La Paz Department,Unknown,El Alto,Unknown,Unknown,Unknown,Unknown
41,"Msambweni, Kenya",-4.454453,39.496880,-4.487012,39.461088,-4.465290,39.481266,APPROXIMATE,-4.454453,39.496880,...,ChIJ4xGXL4-tQRgRkyWdGvj4hR0,"['locality', 'political']",Kenya,Kwale County,Unknown,Msambweni,Unknown,Unknown,Unknown,Unknown
42,"Benin City, Nigeria",6.459025,5.738640,6.236125,5.546293,6.334986,5.603746,APPROXIMATE,6.459025,5.738640,...,ChIJ8azPeWLTQBARoN9YV8AQqoQ,"['locality', 'political']",Nigeria,Edo,Oredo,Benin City,Unknown,Unknown,Unknown,Unknown
43,"Limuru Rd, Nairobi, Kenya",NaN,NaN,NaN,NaN,-1.226668,36.805231,GEOMETRIC_CENTER,-1.225319,36.806580,...,ChIJh4YVjQIXLxgRN3DTrYqBnAI,"['establishment', 'lodging', 'point_of_interest']",Kenya,Nairobi County,Unknown,Nairobi,Kitisuru,Unknown,Limuru Road,Unknown
44,"Tribe Watersports (opposite) Plot 28,, Turtle ...",NaN,NaN,NaN,NaN,-3.375725,39.986635,GEOMETRIC_CENTER,-3.374376,39.987984,...,ChIJR1dhtzyAFRgR0bWNt19WBio,"['establishment', 'point_of_interest', 'store']",Kenya,Unknown,Unknown,Watamu,Unknown,Unknown,Turtle Bay Road,Unknown
45,"Usulutan, El Salvador",13.353713,-88.427668,13.332834,-88.457880,13.345311,-88.442811,APPROXIMATE,13.353713,-88.427668,...,ChIJ73D0kdA5e48RIB_J7tgEUNg,"['locality', 'political']",El Salvador,Usulután Department,Unknown,Usulutan,Unknown,Unknown,Unknown,Unknown
46,"San Gabriel, Ecuador",0.606511,-77.819059,0.585655,-77.839572,0.594895,-77.828151,APPROXIMATE,0.606511,-77.819059,...,ChIJE7e6T7R4KY4R1M7d03xP53A,"['locality', 'political']",Ecuador,Carchi Province,Unknown,San Gabriel,Unknown,Unknown,Unknown,Unknown
47,"Hinigaran, Negros Occidental, Philippines",10.277086,122.859249,10.264840,122.848692,10.271355,122.854985,APPROXIMATE,10.277086,122.859249,...,ChIJ3dtxztKlrjMRJu09d6MQS8Q,"['locality', 'political']",Philippines,Western Visayas,Negros Occidental,Hinigaran,Unknown,Unknown,Unknown,Unknown
48,"Lima, Peru",-11.799988,-76.788340,-12.253289,-77.187219,-12.046373,-77.042754,APPROXIMATE,-11.799988,-76.788340,...,ChIJxz7uGfbFBZERSi5FzLlsIBQ,"['colloquial_area', 'locality', 'political']",Peru,Callao Region,Unknown,Lima,Unknown,Unknown,Unknown,Unknown
49,"Ho Chi Minh City, Vietnam",11.160214,107.026577,10.349370,106.363878,10.823099,106.629664,APPROXIMATE,11.160214,107.026577,...,ChIJ0T2NLikpdTERKxE8d61aX_E,"['locality', 'political']",Vietnam,Ho Chi Minh City,Unknown,Ho Chi Minh City,Unknown,Unknown,Unknown,Unknown

In [66]:
print(df_locations_clean["postal_code"].unique())

<ArrowStringArray>
['Unknown',   '15311',  '735210',  '735211',  '735224',   '72300',   '21000',
  '234501',  '090112',  '170186',
 ...
    '1800',  '767066',  '768042',  '767029',   '20361',    '3132',    '8700',
    '5700',    '2317',   '27915']
Length: 981, dtype: str

In [67]:
print(df_locations_clean.shape)
print(df_locations_clean.columns)
print(df_locations_clean.info())
df_locations_clean.head(50)

(18362, 24)
Index(['formatted_address', 'geometry.bounds.northeast.lat',
       'geometry.bounds.northeast.lng', 'geometry.bounds.southwest.lat',
       'geometry.bounds.southwest.lng', 'geometry.location.lat',
       'geometry.location.lng', 'geometry.location_type',
       'geometry.viewport.northeast.lat', 'geometry.viewport.northeast.lng',
       'geometry.viewport.southwest.lat', 'geometry.viewport.southwest.lng',
       'location_name', 'partial_match', 'place_id', 'types', 'country',
       'state_province', 'district_county', 'city_town', 'neighborhood_suburb',
       'local_area', 'street_name', 'postal_code'],
      dtype='str')
<class 'pandas.DataFrame'>
Index: 18362 entries, 0 to 18364
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   formatted_address                18362 non-null  str
 1   geometry.bounds.northeast.lat    14136 non-null  float64
 2   geometry.bounds.northeast.lng    14136 non-null  float64
 3   geometry.bounds.southwest.lat    14136 non-null  float64
 4   geometry.bounds.southwest.lng    14136 non-null  float64
 5   geometry.location.lat            18362 non-null  float64
 6   geometry.location.lng            18362 non-null  float64
 7   geometry.location_type           18362 non-null  str
 8   geometry.viewport.northeast.lat  18362 non-null  float64
 9   geometry.viewport.northeast.lng  18362 non-null  float64
 10  geometry.viewport.southwest.lat  18362 non-null  float64
 11  geometry.viewport.southwest.lng  18362 non-null  float64
 12  location_name                    18362 non-null  str
 13  partial_match                    18362 non-null  str
 14  place_id                         18362 non-null  str
 15  types                            18362 non-null  str
 16  country                          18362 non-null  str
 17  state_province                   18362 non-null  str
 18  district_county                  18362 non-null  str
 19  city_town                        18362 non-null  str
 20  neighborhood_suburb              18362 non-null  str
 21  local_area                       18362 non-null  str
 22  street_name                      18362 non-null  str
 23  postal_code                      18362 non-null  str
dtypes: float64(10), str(14)
memory usage: 7.3 MB
None

,formatted_address,geometry.bounds.northeast.lat,geometry.bounds.northeast.lng,geometry.bounds.southwest.lat,geometry.bounds.southwest.lng,geometry.location.lat,geometry.location.lng,geometry.location_type,geometry.viewport.northeast.lat,geometry.viewport.northeast.lng,...,place_id,types,country,state_province,district_county,city_town,neighborhood_suburb,local_area,street_name,postal_code
0,"Managua, Nicaragua",12.175357,-86.125088,12.019961,-86.391833,12.114993,-86.236174,APPROXIMATE,12.175357,-86.125088,...,ChIJC4gH2Q1WcY8RakxPFKL0Xmw,"['locality', 'political']",Nicaragua,Managua Department,Unknown,Managua,Unknown,Unknown,Unknown,Unknown
1,"Lahore, Pakistan",31.698486,74.587397,31.267394,74.115539,31.520370,74.358747,APPROXIMATE,31.698486,74.587397,...,ChIJ2QeB5YMEGTkRYiR-zGy-OsI,"['locality', 'political']",Pakistan,Punjab,Lahore,Lahore,Unknown,Unknown,Unknown,Unknown
2,"Kaduna, Nigeria",10.616996,7.508812,10.397157,7.349789,10.510464,7.416505,APPROXIMATE,10.616996,7.508812,...,ChIJdRc3NFg1TRARdOG_mpeVAUg,"['locality', 'political']",Nigeria,Kaduna,Unknown,Kaduna,Unknown,Unknown,Unknown,Unknown
3,"Cusco, Peru",-13.497391,-71.853332,-13.562648,-72.025166,-13.531950,-71.967463,APPROXIMATE,-13.497391,-71.853332,...,ChIJMYRZJtjVbZERXTEYI8yWqSo,"['locality', 'political']",Peru,Cusco,Cusco,Cusco,Unknown,Unknown,Unknown,Unknown
4,"León, Nicaragua",12.460966,-86.843405,12.407026,-86.920753,12.431553,-86.872215,APPROXIMATE,12.460966,-86.843405,...,ChIJd3qPu5IfcY8RPDHqZG_AtTo,"['locality', 'political']",Nicaragua,León Department,Unknown,León,Unknown,Unknown,Unknown,Unknown
5,"Dar es Salaam, Tanzania",-6.588899,39.481711,-6.950283,39.026871,-6.792354,39.208328,APPROXIMATE,-6.588899,39.481711,...,ChIJ8dabFq5LXBgR3aGGoCZrD5Q,"['locality', 'political']",Tanzania,Dar es Salaam,Kinondoni,Dar es Salaam,Unknown,Unknown,Unknown,Unknown
6,"La Paz, Bolivia",-16.424560,-68.011293,-16.616865,-68.236862,-16.489689,-68.119294,APPROXIMATE,-16.424560,-68.011293,...,ChIJD6T1BArfXpERs4pFtHb821c,"['locality', 'political']",Bolivia,La Paz Department,Unknown,La Paz,Unknown,Unknown,Unknown,Unknown
7,"Kampala, Uganda",0.413199,32.689280,0.212860,32.508971,0.347596,32.582520,APPROXIMATE,0.413199,32.689280,...,ChIJm7N0nQ-8fRcR7G9r2T2QOEU,"['locality', 'political']",Uganda,Central Region,Kampala,Kampala,Unknown,Unknown,Unknown,Unknown
8,"Ayacucho, Peru",-13.119257,-74.180044,-13.197473,-74.244564,-13.163874,-74.223564,APPROXIMATE,-13.119257,-74.180044,...,ChIJ6b6y9Yh9EpERbqFwOoTLs-k,"['locality', 'political']",Peru,Ayacucho,Huamanga,Ayacucho,Unknown,Unknown,Unknown,Unknown
9,"Rawalpindi, Pakistan",33.664704,73.153278,33.458325,72.889134,33.565111,73.016914,APPROXIMATE,33.664704,73.153278,...,ChIJy5pBdImU3zgRD9MyFn41hAk,"['locality', 'political']",Pakistan,Punjab,Rawalpindi,Rawalpindi,Unknown,Unknown,Unknown,Unknown
10,"Kabankalan, Negros Occidental, Philippines",10.063262,122.985849,9.576037,122.717285,9.913412,122.853576,APPROXIMATE,10.063262,122.985849,...,ChIJpW1BAiUTrDMR7qeRyQupslw,"['locality', 'political']",Philippines,Western Visayas,Negros Occidental,Kabankalan,Unknown,Unknown,Unknown,Unknown
11,"Kitale, Kenya",1.063417,35.041710,0.968692,34.967872,1.019089,35.002305,APPROXIMATE,1.063417,35.041710,...,ChIJxZPE-P8mghcRXPMRqBD5U0A,"['locality', 'political']",Kenya,Trans-Nzoia County,Unknown,Kitale,Unknown,Unknown,Unknown,Unknown
12,"Eldoret, Kenya",0.578829,35.314682,0.444684,35.223742,0.514277,35.269780,APPROXIMATE,0.578829,35.314682,...,ChIJNfX5N64BgRcRIAj88H0z2-I,"['locality', 'political']",Kenya,Uasin Gishu County,Unknown,Eldoret,Unknown,Unknown,Unknown,Unknown
13,"Narra, Palawan, Philippines",9.460746,118.518619,9.099724,118.066978,9.250630,118.346195,APPROXIMATE,9.460746,118.518619,...,ChIJD4XG4hs2NTIRHEx_KKExwv0,"['locality', 'political']",Philippines,MIMAROPA,Palawan,Narra,Unknown,Unknown,Unknown,Unknown
14,"Pucallpa, Peru",-8.316900,-74.518461,-8.433319,-74.644976,-8.392862,-74.582617,APPROXIMATE,-8.316900,-74.518461,...,ChIJYUTr8vO8o5ERQ9-UtZhiAEk,"['locality', 'political']",Peru,Ucayali,Coronel Portillo,Pucallpa,Unknown,Unknown,Unknown,Unknown
15,"Likoni, Mombasa, Kenya",-4.079346,39.674774,-4.099795,39.647079,-4.092902,39.661445,APPROXIMATE,-4.079346,39.674774,...,ChIJLXFdP1cTQBgRbjQzj9uzYYA,"['political', 'sublocality', 'sublocality_leve...",Kenya,Coast,Unknown,Mombasa,Likoni,Unknown,Unknown,Unknown
16,"Brooke's Point, Palawan, Philippines",8.998009,118.019943,8.668936,117.679367,8.818934,117.784246,APPROXIMATE,8.998009,118.019943,...,ChIJZecGp8D-NDIRAWTMMKuoFgY,"['locality', 'political']",Philippines,MIMAROPA,Palawan,Brooke's Point,Unknown,Unknown,Unknown,Unknown
17,"Portoviejo, Ecuador",-0.960572,-79.933777,-1.136324,-80.580254,-1.054723,-80.452490,APPROXIMATE,-0.960572,-79.933777,...,ChIJpWeRNLPyK5AR7n7rE-WA67U,"['locality', 'political']",Ecuador,Manabí Province,Unknown,Portoviejo,Unknown,Unknown,Unknown,Unknown
18,"Thanh Hóa, Thanh Hoa, Vietnam",19.884508,105.862949,19.732916,105.719161,19.806692,105.785182,APPROXIMATE,19.884508,105.862949,...,ChIJdyJ-I_73NjEROiH8ezYyOKE,"['locality', 'political']",Vietnam,Thanh Hoa,Unknown,Thanh Hóa,Unknown,Unknown,Unknown,Unknown
19,"Bais City, Negros Oriental, Philippines",9.682407,123.166351,9.535664,122.891135,9.591569,123.121179,APPROXIMATE,9.682407,123.166351,...,ChIJyTVBTCt5rDMRouQAUsvj6CU,"['locality', 'political']",Philippines,Central Visayas,Negros Oriental,Bais City,Unknown,Unknown,Unknown,Unknown
20,"Cordova, Cebu, Philippines",10.279862,124.009982,10.184658,123.893656,10.243864,123.941552,APPROXIMATE,10.279862,124.009982,...,ChIJi0WpTF-aqTMRnQrxQZG5VAs,"['locality', 'political']",Philippines,Central Visayas,Cebu,Cordova,Unknown,Unknown,Unknown,Unknown
21,"Medellin, Antioquia, Colombia",6.373637,-75.473410,6.163719,-75.719374,6.244203,-75.581212,APPROXIMATE,6.373637,-75.473410,...,ChIJ291STu8oRI4RcqxwksPWL3I,"['administrative_area_level_2', 'political']",Colombia,Antioquia,Medellin,Unknown,Unknown,Unknown,Unknown,Unknown
22,"Barranquilla, Atlantico, Colombia",11.046332,-74.758539,10.921292,-74.877496,11.004107,-74.806981,APPROXIMATE,11.046332,-74.758539,...,ChIJBeYq0UQt9I4Rshe5gUWEMyY,"['locality', 'political']",Colombia,Atlantico,Barranquilla,Barranquilla,Unknown,Unknown,Unknown,Unknown
23,"Nakuru, Kenya",-0.208311,36.197237,-0.423313,35.960484,-0.303099,36.080026,APPROXIMATE,-0.208311,36.197237,...,ChIJ7wthz5CNKRgRGsJ8vDMY8vI,"['locality', 'political']",Kenya,Nakuru County,Unknown,Nakuru,Unknown,Unknown,Unknown,Unknown
24,"Quezon, Palawan, Philippines",9.553609,118.335114,8.998348,117.718162,9.418463,118.252662,APPROXIMATE,9.553609,118.335114,...,ChIJi4uruikvNTIRpJnR_HZgatQ,"['locality', 'political']",Philippines,MIMAROPA,Palawan,Quezon,Unknown,Unknown,Unknown,Unknown
25,"Palo, Leyte, Philippines",11.192211,125.021668,11.095704,124.911632,11.158383,124.991888,APPROXIMATE,11.192211,125.021668,...,ChIJK0FOiWbYBzMRM0PS7unDgsA,"['locality', 'political']",Philippines,Eastern Visayas,Leyte,Palo,Unknown,Unknown,Unknown,Unknown
26,"Masaya, Nicaragua",11.997598,-86.072121,11.952426,-86.113329,11.970448,-86.088637,APPROXIMATE,11.997598,-86.072121,...,ChIJKRUckR0GdI8R0moxUGHN1vI,"['locality', 'political']",Nicaragua,Masaya Department,Unknown,Masaya,Unknown,Unknown,Unknown,Unknown
27,"Kisauni, Mombasa, Kenya",-4.011375,39.711655,-4.038996,39.673308,-4.022620,39.687933,APPROXIMATE,-4.011375,39.711655,...,ChIJjb0Tkn8NQBgRuvIU_xl3SNc,"['political', 'sublocality', 'sublocality_leve...",Kenya,Coast,Unknown,Mombasa,Kisauni,Unknown,Unknown,Unknown
28,"Kasese, Uganda",0.193290,30.107088,0.150289,30.061589,0.169899,30.078078,APPROXIMATE,0.193290,30.107088,...,ChIJ27nqCi3yYRcRcP7Ml11wWSQ,"['locality', 'political']",Uganda,Western Region,Kasese,Kasese,Unknown,Unknown,Unknown,Unknown
29,"Khujand, Tajikistan",40.335161,69.727993,40.233674,69.545860,40.267515,69.645288,APPROXIMATE,40.335161,69.727993,...,ChIJDT6rw92ysTgRN-5Pz0XcTB8,"['locality', 'political']",Tajikistan,Sughd Province,Unknown,Khujand,Unknown,Unknown,Unknown,Unknown
30,"San Miguel, El Salvador",13.526815,-88.112068,13.430220,-88.226110,13.479292,-88.177918,APPROXIMATE,13.526815,-88.112068,...,ChIJqw2DvHAqe48RklXsbkCcrHY,"['locality', 'political']",El Salvador,San Miguel Department,Unknown,San Miguel,Unknown,Unknown,Unknown,Unknown
31,"Kisumu, Kenya",0.037508,34.901247,-0.187454,34.575090,-0.091702,34.767957,APPROXIMATE,0.037508,34.901247,...,ChIJHchKrTekKhgR0o0k1jmkEiA,"['locality', 'political']",Kenya,Kisumu County,Unknown,Kisumu,Unknown,Unknown,Unknown,Unknown
32,"Phnom Penh, Cambodia",11.736327,105.067577,11.422401,104.712796,11.544873,104.892167,APPROXIMATE,11.736327,105.067577,...,ChIJ42tqxz1RCTERuyW1WugOAZw,"['locality', 'political']",Cambodia,Phnom Penh,Unknown,Phnom Penh,Unknown,Unknown,Unknown,Unknown
33,"Fort Portal, Uganda",0.679944,30.296460,0.625499,30.253374,0.654626,30.280117,APPROXIMATE,0.679944,30.296460,...,ChIJwUHNPELaYxcRUEdocKxcEbM,"['locality', 'political']",Uganda,Western Region,Kabarole,Fort Portal,Unknown,Unknown,Unknown,Unknown
34,"Boane District, Mozambique",-25.769004,32.498644,-26.287666,32.183632,-26.112894,32.310752,APPROXIMATE,-25.769004,32.498644,...,ChIJAf1L4p195h4RuuDVZG6L8rQ,"['administrative_area_level_2', 'political']",Mozambique,Maputo Province,Boane District,Unknown,Unknown,Unknown,Unknown,Unknown
35,"Dumaguete, Negros Oriental, Philippines",9.332478,123.313798,9.258986,123.250337,9.306840,123.305447,APPROXIMATE,9.332478,123.313798,...,ChIJ96COeNtuqzMR-zf8W5v-ndc,"['locality', 'political']",Philippines,Central Visayas,Negros Oriental,Dumaguete,Unknown,Unknown,Unknown,Unknown
36,"Tarma, Peru",-11.391523,-75.660267,-11.481202,-75.714941,-11.419335,-75.688949,APPROXIMATE,-11.391523,-75.660267,...,ChIJGXWgCpQgCZERwVdx0EBd98c,"['locality', 'political']",Peru,Junin,Tarma Province,Tarma,Unknown,Unknown,Unknown,Unknown
37,"Cusco, Peru",-13.497391,-71.853332,-13.562648,-72.025166,-13.531950,-71.967463,APPROXIMATE,-13.497391,-71.853332,...,ChIJMYRZJtjVbZERXTEYI8yWqSo,"['locality', 'political']",Peru,Cusco,Cusco,Cusco,Unknown,Unknown,Unknown,Unknown
38,"Multan, Pakistan",30.310533,71.645387,30.051979,71.303930,30.157458,71.524915,APPROXIMATE,30.310533,71.645387,...,ChIJ2afeeFcxOzkRL9RVTscv17o,"['locality', 'political']",Pakistan,Punjab,Multan,Multan,Unknown,Unknown,Unknown,Unknown
39,"Talibon, Bohol, Philippines",10.257155,124.368153,10.027008,124.214162,10.157695,124.264387,APPROXIMATE,10.257155,124.368153,...,ChIJn0ymbLrxqTMRm7E7XdDMEWo,"['locality', 'political']",Philippines,Central Visayas,Bohol,Talibon,Unknown,Unknown,Unknown,Unknown
40,"El Alto, Bolivia",-16.444216,-68.129482,-16.649586,-68.298908,-16.500094,-68.214686,APPROXIMATE,-16.444216,-68.129482,...,ChIJcyQuhL7eXpERj534Fy-KHzo,"['locality', 'political']",Bolivia,La Paz Department,Unknown,El Alto,Unknown,Unknown,Unknown,Unknown
41,"Msambweni, Kenya",-4.454453,39.496880,-4.487012,39.461088,-4.465290,39.481266,APPROXIMATE,-4.454453,39.496880,...,ChIJ4xGXL4-tQRgRkyWdGvj4hR0,"['locality', 'political']",Kenya,Kwale County,Unknown,Msambweni,Unknown,Unknown,Unknown,Unknown
42,"Benin City, Nigeria",6.459025,5.738640,6.236125,5.546293,6.334986,5.603746,APPROXIMATE,6.459025,5.738640,...,ChIJ8azPeWLTQBARoN9YV8AQqoQ,"['locality', 'political']",Nigeria,Edo,Oredo,Benin City,Unknown,Unknown,Unknown,Unknown
43,"Limuru Rd, Nairobi, Kenya",NaN,NaN,NaN,NaN,-1.226668,36.805231,GEOMETRIC_CENTER,-1.225319,36.806580,...,ChIJh4YVjQIXLxgRN3DTrYqBnAI,"['establishment', 'lodging', 'point_of_interest']",Kenya,Nairobi County,Unknown,Nairobi,Kitisuru,Unknown,Limuru Road,Unknown
44,"Tribe Watersports (opposite) Plot 28,, Turtle ...",NaN,NaN,NaN,NaN,-3.375725,39.986635,GEOMETRIC_CENTER,-3.374376,39.987984,...,ChIJR1dhtzyAFRgR0bWNt19WBio,"['establishment', 'point_of_interest', 'store']",Kenya,Unknown,Unknown,Watamu,Unknown,Unknown,Turtle Bay Road,Unknown
45,"Usulutan, El Salvador",13.353713,-88.427668,13.332834,-88.457880,13.345311,-88.442811,APPROXIMATE,13.353713,-88.427668,...,ChIJ73D0kdA5e48RIB_J7tgEUNg,"['locality', 'political']",El Salvador,Usulután Department,Unknown,Usulutan,Unknown,Unknown,Unknown,Unknown
46,"San Gabriel, Ecuador",0.606511,-77.819059,0.585655,-77.839572,0.594895,-77.828151,APPROXIMATE,0.606511,-77.819059,...,ChIJE7e6T7R4KY4R1M7d03xP53A,"['locality', 'political']",Ecuador,Carchi Province,Unknown,San Gabriel,Unknown,Unknown,Unknown,Unknown
47,"Hinigaran, Negros Occidental, Philippines",10.277086,122.859249,10.264840,122.848692,10.271355,122.854985,APPROXIMATE,10.277086,122.859249,...,ChIJ3dtxztKlrjMRJu09d6MQS8Q,"['locality', 'political']",Philippines,Western Visayas,Negros Occidental,Hinigaran,Unknown,Unknown,Unknown,Unknown
48,"Lima, Peru",-11.799988,-76.788340,-12.253289,-77.187219,-12.046373,-77.042754,APPROXIMATE,-11.799988,-76.788340,...,ChIJxz7uGfbFBZERSi5FzLlsIBQ,"['colloquial_area', 'locality', 'political']",Peru,Callao Region,Unknown,Lima,Unknown,Unknown,Unknown,Unknown
49,"Ho Chi Minh City, Vietnam",11.160214,107.026577,10.349370,106.363878,10.823099,106.629664,APPROXIMATE,11.160214,107.026577,...,ChIJ0T2NLikpdTERKxE8d61aX_E,"['locality', 'political']",Vietnam,Ho Chi Minh City,Unknown,Ho Chi Minh City,Unknown,Unknown,Unknown,Unknown

In [68]:
# Re-Gather all structural metrics
missing_count = df_locations_clean.isnull().sum()
missing_percent = (df_locations_clean.isnull().sum() / len(df_locations_clean)) * 100
column_types = df_locations_clean.dtypes

# Combine them into a single DataFrame
full_report_locations = pd.DataFrame({
    "Data Type": column_types,
    "Missing Count": missing_count,
    "Missing %": missing_percent
})

# Note: We do not sort by "Missing %" here so that the columns and rows stay in their original order (0 to 102), making slicing accurate.

# Columns 1 to 25
print(f"Total Rows, {df_locations_clean.shape[0]}")
print(f"Total Columns, {df_locations_clean.shape[1]}")
print(f"Exact Duplicate Rows, {df_locations_clean.duplicated().sum()}")

print(full_report_locations.iloc[0:25])

# Strip hidden spaces from categorical string columns
locations_clean_cols = ['formatted_address', 'geometry.bounds.northeast.lat',
       'geometry.bounds.northeast.lng', 'geometry.bounds.southwest.lat',
       'geometry.bounds.southwest.lng', 'geometry.location.lat',
       'geometry.location.lng', 'geometry.location_type',
       'geometry.viewport.northeast.lat', 'geometry.viewport.northeast.lng',
       'geometry.viewport.southwest.lat', 'geometry.viewport.southwest.lng',
       'location_name', 'partial_match', 'place_id', 'types', 'country',
       'state_province', 'district_county', 'city_town', 'neighborhood_suburb',
       'local_area', 'street_name', 'postal_code']

Total Rows, 18362
Total Columns, 24
Exact Duplicate Rows, 0
                                Data Type  Missing Count  Missing %
formatted_address                     str              0   0.000000
geometry.bounds.northeast.lat     float64           4226  23.014922
geometry.bounds.northeast.lng     float64           4226  23.014922
geometry.bounds.southwest.lat     float64           4226  23.014922
geometry.bounds.southwest.lng     float64           4226  23.014922
geometry.location.lat             float64              0   0.000000
geometry.location.lng             float64              0   0.000000
geometry.location_type                str              0   0.000000
geometry.viewport.northeast.lat   float64              0   0.000000
geometry.viewport.northeast.lng   float64              0   0.000000
geometry.viewport.southwest.lat   float64              0   0.000000
geometry.viewport.southwest.lng   float64              0   0.000000
location_name                         str              0   0.000000
partial_match                         str              0   0.000000
place_id                              str              0   0.000000
types                                 str              0   0.000000
country                               str              0   0.000000
state_province                        str              0   0.000000
district_county                       str              0   0.000000
city_town                             str              0   0.000000
neighborhood_suburb                   str              0   0.000000
local_area                            str              0   0.000000
street_name                           str              0   0.000000
postal_code                           str              0   0.000000

In [69]:
# Fill the missing bounding coordinates with NaN to maintain float64 integrity
bound_cols = [
    "geometry.bounds.northeast.lat", "geometry.bounds.northeast.lng",
    "geometry.bounds.southwest.lat", "geometry.bounds.southwest.lng"
]
for col in bound_cols:
    df_locations_clean[col] = df_locations_clean[col].fillna(-999.0)

In [70]:
# Create a local reference copy for the export step
df_locations_clean = df_locations_clean.copy()

# Export the final fully structured locations dataset
df_locations_clean.to_csv( r"C:\Users\sanjay\OneDrive\Desktop\scratchpad_archive\002.kiva_loans_datasets\cleaned_locations.csv", index=False)

print("Locations dataset clean state export successful!")

Locations dataset clean state export successful!